// Code generated by cmd/acpgen from spec/acp/meta.json. DO NOT EDIT.

package acp

// SchemaProtocolVersion is the ACP protocol version the vendored schema describes.
const SchemaProtocolVersion ProtocolVersion = 1

// Methods the client calls on the agent.
const (
	MethodAuthenticate           = "authenticate"
	MethodInitialize             = "initialize"
	MethodLogout                 = "logout"
	MethodSessionCancel          = "session/cancel"
	MethodSessionClose           = "session/close"
	MethodSessionDelete          = "session/delete"
	MethodSessionList            = "session/list"
	MethodSessionLoad            = "session/load"
	MethodSessionNew             = "session/new"
	MethodSessionPrompt          = "session/prompt"
	MethodSessionResume          = "session/resume"
	MethodSessionSetConfigOption = "session/set_config_option"
	MethodSessionSetMode         = "session/set_mode"
)

// Methods the agent calls on the client.
const (
	MethodElicitationComplete      = "elicitation/complete"
	MethodElicitationCreate        = "elicitation/create"
	MethodFsReadTextFile           = "fs/read_text_file"
	MethodFsWriteTextFile          = "fs/write_text_file"
	MethodSessionRequestPermission = "session/request_permission"
	MethodSessionUpdate            = "session/update"
	MethodTerminalCreate           = "terminal/create"
	MethodTerminalKill             = "terminal/kill"
	MethodTerminalOutput           = "terminal/output"
	MethodTerminalRelease          = "terminal/release"
	MethodTerminalWaitForExit      = "terminal/wait_for_exit"
)

// Methods either side may send.
const (
	MethodCancelRequest = "$/cancel_request"
)
