// Code generated by cmd/protogen; DO NOT EDIT.

export interface ACPCapabilities {
  "load_session"?: boolean;
  "resume_session"?: boolean;
  "close_session"?: boolean;
  "additional_directories"?: boolean;
}

export interface ACPFrameRecord {
  "at": number;
  "frame": unknown;
  "replayed"?: boolean;
  "redacted"?: boolean;
  "truncated"?: boolean;
}

export interface ACPRecordAssembler {
}

export interface Agent {
  "id": string;
  "tenant": string;
  "owner": string;
  "name"?: string;
  "ws": string;
  "owns_ws"?: boolean;
  "spec": AgentSpec;
  "mode": string;
  "acp_session_id"?: string;
  "capabilities"?: ACPCapabilities | null;
  "status": string;
  "status_reason"?: string;
  "inbox": Array<AgentMessage>;
  "runs": Array<AgentRun>;
  "turns": number;
  "parent"?: string;
  "forked_from"?: string;
  "policy": AgentPolicy;
  "transcript_session"?: string;
  "transcript_node"?: string;
  "transcript_next"?: number;
  "transcript_first"?: number;
  "transcript_bytes"?: number;
  "pending_approvals"?: number;
  "url"?: string;
  "created_at": number;
  "updated_at": number;
  "wake_timer"?: string;
  "idle_since"?: number;
  "failures"?: number;
  "parent_notified"?: boolean;
}

export interface AgentApprovalDecidedReq {
  "agent": string;
  "run": string;
  "approval": string;
  "decision": ApprovalDecision;
}

export interface AgentCreateReq {
  "name"?: string;
  "ws"?: string;
  "workspace"?: WorkspaceSpec | null;
  "spec": AgentSpec;
  "policy": AgentPolicy;
  "parent"?: string;
  "acp_session_id"?: string;
  "idem"?: string;
}

export interface AgentDeliverReq {
  "agent": string;
  "run": string;
  "message": AgentMessage;
}

export interface AgentForkReq {
  "id": string;
  "name"?: string;
  "task"?: string;
  "policy"?: AgentPolicy | null;
  "idem"?: string;
}

export interface AgentGetReq {
  "id": string;
  "idem"?: string;
}

export interface AgentListReq {
  "status"?: string;
  "ws"?: string;
  "parent"?: string;
}

export interface AgentListRes {
  "agents": Array<Agent>;
}

export interface AgentMessage {
  "id": string;
  "kind": string;
  "text": string;
  "by"?: string;
  "at": number;
}

export interface AgentMessageReq {
  "id": string;
  "text": string;
  "kind"?: string;
  "idem"?: string;
}

export interface AgentMessageRes {
  "agent": Agent;
  "message": AgentMessage;
  "degraded"?: boolean;
  "woken"?: boolean;
}

export interface AgentPolicy {
  "sleep_after_sec"?: number;
  "approve"?: string;
  "max_turns"?: number;
  "start_at"?: number;
}

export interface AgentReport {
  "agent": string;
  "run": string;
  "ws": string;
  "gen": number;
  "seq": number;
  "kind": string;
  "at": number;
  "transcript"?: string;
  "acp_session_id"?: string;
  "capabilities"?: ACPCapabilities | null;
  "loaded"?: boolean;
  "message"?: string;
  "stop_reason"?: string;
  "error"?: string;
  "exit_code"?: number;
  "cancelled"?: boolean;
  "tool_call"?: string;
  "tool_kind"?: string;
  "tool_title"?: string;
  "tool_status"?: string;
  "locations"?: Array<string>;
  "approval"?: Approval | null;
  "usage"?: AgentUsage | null;
  "chunks"?: Array<TranscriptChunk>;
}

export interface AgentRun {
  "id": string;
  "attempt": number;
  "node"?: string;
  "gen"?: number;
  "state": string;
  "transcript"?: string;
  "loaded"?: boolean;
  "started_at"?: number;
  "finished_at"?: number;
  "stop_reason"?: string;
  "error"?: string;
  "turns": number;
  "last_report"?: number;
  "turn_message"?: string;
}

export interface AgentRunCancelReq {
  "agent": string;
  "run": string;
  "reason"?: string;
}

export interface AgentRunReq {
  "agent": string;
  "run": string;
  "attempt": number;
  "ws": string;
  "gen": number;
  "tenant": string;
  "owner": string;
  "spec": AgentSpec;
  "policy": AgentPolicy;
  "mode": string;
  "acp_session_id"?: string;
  "messages": Array<AgentMessage>;
}

export interface AgentRunRes {
  "transcript": string;
}

export interface AgentSpec {
  "recipe": string;
  "recipe_yaml"?: string;
  "task": string;
  "providers"?: Array<string>;
  "primary"?: string;
  "model"?: string;
  "sandbox"?: string;
  "acp_command"?: Array<string>;
  "auth"?: string;
  "mode"?: string;
}

export interface AgentTranscriptReq {
  "id": string;
  "from"?: number;
  "limit"?: number;
}

export interface AgentTranscriptRes {
  "records": Array<TranscriptRecord>;
  "next": number;
  "gap"?: TranscriptGap | null;
  "done"?: boolean;
}

export interface AgentUsage {
  "input"?: number;
  "output"?: number;
}

export interface AgentWakeReq {
  "id": string;
  "by"?: string;
  "idem"?: string;
}

export interface Approval {
  "id": string;
  "tenant": string;
  "owner": string;
  "agent"?: string;
  "ws"?: string;
  "run"?: string;
  "principal"?: string;
  "rule"?: string;
  "host"?: string;
  "method"?: string;
  "path_hash"?: string;
  "body_hash"?: string;
  "fingerprint"?: string;
  "kind": string;
  "title"?: string;
  "tool_call"?: string;
  "tool_kind"?: string;
  "locations"?: Array<string>;
  "options"?: Array<ApprovalOption>;
  "detail"?: unknown;
  "status": string;
  "decision"?: ApprovalDecision | null;
  "delivered_at"?: number;
  "created_at": number;
  "updated_at": number;
  "expires_at"?: number;
}

export interface ApprovalDecideReq {
  "id": string;
  "option"?: string;
  "denied"?: boolean;
  "content"?: unknown;
  "remember"?: string;
  "idem"?: string;
}

export interface ApprovalDecision {
  "option"?: string;
  "denied"?: boolean;
  "content"?: unknown;
  "by": string;
  "at": number;
  "remember"?: string;
}

export interface ApprovalGetReq {
  "id": string;
}

export interface ApprovalListReq {
  "agent"?: string;
  "kind"?: string;
  "status"?: string;
}

export interface ApprovalListRes {
  "approvals": Array<Approval>;
}

export interface ApprovalOption {
  "id": string;
  "name"?: string;
  "kind"?: string;
}

export interface AuditPolicy {
  "required"?: boolean;
}

export interface AuthzRevocation {
  "rev": number;
  "principal": string;
}

export interface BackendDescriptor {
  "name": string;
  "security": BackendSecurityCaps;
  "runtime": RuntimeCaps;
}

export interface BackendSecurityCaps {
  "isolation": string;
  "multi_tenant": boolean;
  "sibling_isolation": boolean;
  "egress_mode": string;
  "broker_identity": string;
  "filesystem_boundary": string;
  "network_namespace": boolean;
  "device_isolation": boolean;
}

export interface Base {
  "name": string;
  "tenant": string;
  "owner": string;
  "artifact": string;
  "workspace"?: string;
  "bytes"?: number;
  "created_at": number;
}

export interface BaseCreateReq {
  "name": string;
  "artifact": string;
  "workspace"?: string;
  "idem"?: string;
}

export interface BaseListRes {
  "bases": Array<Base>;
}

export interface BaseRemoveReq {
  "name": string;
  "idem"?: string;
}

export interface BindingLease {
  "id": string;
  "secret": string;
  "destinations": Array<string>;
  "shape"?: string;
  "principals"?: Array<string>;
  "expires_at": number;
  "placeholder"?: string;
}

export interface BindingLeaseReq {
  "ws": string;
  "gen"?: number;
}

export interface BindingLeaseRes {
  "leases": Array<BindingLease>;
}

export interface Budget {
  "id": string;
  "tenant"?: string;
  "attach_to": string;
  "attach_id": string;
  "window": string;
  "max_requests"?: number;
  "max_tokens"?: number;
  "max_estimated_cost_micros"?: number;
  "created_at"?: number;
  "updated_at"?: number;
}

export interface BudgetCreateReq {
  "budget": Budget;
  "idem"?: string;
}

export interface BudgetListReq {
}

export interface BudgetListRes {
  "budgets": Array<Budget>;
}

export interface BudgetRemoveReq {
  "id": string;
  "idem"?: string;
}

export interface BudgetReservation {
  "id"?: string;
  "tracked"?: boolean;
  "budget_ids"?: Array<string>;
  "unmetered_reason"?: string;
  "expires_at"?: number;
  "denied"?: boolean;
  "limit"?: string;
}

export interface BudgetReserveReq {
  "key": string;
  "ws": string;
  "gen": number;
  "principal"?: string;
  "bindings"?: Array<string>;
  "provider": string;
  "model"?: string;
  "input_tokens"?: number;
  "max_output_tokens"?: number;
  "metered"?: boolean;
}

export interface BudgetSettleReq {
  "reservation": string;
  "mode": string;
  "input_tokens"?: number;
  "output_tokens"?: number;
}

export interface BudgetSettlement {
  "reservation": string;
  "mode": string;
  "tokens"?: number;
  "estimated_cost_micros"?: number;
  "estimated_cost_unavailable"?: boolean;
  "usage_exceeded_reservation"?: boolean;
}

export interface ChildSummary {
  "child": string;
  "name"?: string;
  "status": string;
  "reason"?: string;
  "turns": number;
  "ws": string;
  "url"?: string;
}

export interface ChunkBody {
  "st": number;
  "d"?: Uint8Array;
}

export interface ControlDiag {
  "now": number;
  "uptime_sec": number;
  "version"?: string;
  "ws_state": Record<string, number>;
  "nodes_total": number;
  "nodes_online": number;
  "timers_pending": number;
  "timers_fired": number;
  "timers_max"?: number;
  "mutation_records"?: number;
  "mutation_records_max"?: number;
  "event_seq": number;
  "event_oldest"?: number;
  "events_max"?: number;
  "requests_active_max"?: number;
  "bindings"?: Array<string>;
  "artifact_count": number;
  "artifact_bytes": number;
  "artifact_reserved_bytes"?: number;
  "artifact_reserved_objects"?: number;
  "artifact_max_bytes"?: number;
  "artifact_max_objects"?: number;
  "workspaces_per_tenant_max"?: number;
  "workspaces_per_subject_max"?: number;
  "db_integrity"?: string;
  "lease_sec": number;
  "metrics"?: Record<string, number>;
  "findings"?: Array<Finding>;
}

export interface DiagReq {
  "verify"?: boolean;
}

export interface EgressApprovalReq {
  "ws": string;
  "gen": number;
  "principal": string;
  "rule": string;
  "host": string;
  "method": string;
  "path_hash": string;
  "body_hash": string;
  "fingerprint": string;
  "wait_ms"?: number;
}

export interface EgressApprovalRes {
  "id": string;
  "status": string;
  "allowed"?: boolean;
  "expires_at"?: number;
}

export interface EgressRule {
  "id": string;
  "mode"?: string;
  "connector"?: string;
  "protocol": string;
  "hosts"?: Array<string>;
  "ports"?: Array<number>;
  "methods"?: Array<string>;
  "path_prefixes"?: Array<string>;
  "max_requests"?: number;
  "max_request_bytes"?: number;
  "max_response_bytes"?: number;
  "redact"?: Array<string>;
  "shared_state"?: string;
  "repos"?: Array<string>;
  "push"?: boolean;
}

export interface Error {
  "code": string;
  "msg"?: string;
  "oldest"?: number;
}

export interface Event {
  "seq": number;
  "at": number;
  "stream"?: string;
  "principal"?: string;
  "node"?: string;
  "event_id"?: string;
  "received_at"?: number;
  "observed_at"?: number;
  "origin"?: string;
  "actor"?: string;
  "tenant"?: string;
  "workspace"?: string;
  "generation"?: number;
  "session"?: string;
  "operation_id"?: string;
  "producer_seq"?: number;
  "type": string;
  "payload"?: Uint8Array;
  "cause"?: number;
}

export interface EventPost {
  "events": Array<Event>;
  "sub"?: string;
}

export interface EventsStopReq {
  "sub"?: string;
}

export interface EventsTailReq {
  "from": number;
  "follow": boolean;
  "ws"?: string;
  "sub"?: string;
}

export interface ExitInfo {
  "code": number;
  "signal"?: string;
  "error"?: string;
  "reason"?: string;
}

export interface FSApplyTarReq {
  "ws": string;
  "artifact": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSApplyTarRes {
  "files": number;
  "dirs": number;
  "bytes": number;
}

export interface FSEdit {
  "old": string;
  "new": string;
  "all"?: boolean;
}

export interface FSEditReq {
  "ws": string;
  "path": string;
  "edits": Array<FSEdit>;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSEditRes {
  "replacements": number;
}

export interface FSEntry {
  "name": string;
  "size": number;
  "mode": number;
  "dir": boolean;
  "mtime": number;
  "link"?: boolean;
}

export interface FSListReq {
  "ws": string;
  "path": string;
  "grant"?: Grant | null;
}

export interface FSListRes {
  "entries": Array<FSEntry>;
}

export interface FSMatch {
  "path": string;
  "line": number;
  "text": string;
}

export interface FSMkdirReq {
  "ws": string;
  "path": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSReadReq {
  "ws": string;
  "path": string;
  "offset"?: number;
  "limit"?: number;
  "grant"?: Grant | null;
}

export interface FSReadRes {
  "d": Uint8Array;
  "size": number;
  "eof": boolean;
}

export interface FSRemoveReq {
  "ws": string;
  "path": string;
  "recursive"?: boolean;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSRenameReq {
  "ws": string;
  "from": string;
  "to": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSSearchReq {
  "ws": string;
  "path": string;
  "pattern": string;
  "glob"?: string;
  "max"?: number;
  "grant"?: Grant | null;
}

export interface FSSearchRes {
  "matches": Array<FSMatch>;
  "truncated": boolean;
}

export interface FSStatRes {
  "entry": FSEntry;
}

export interface FSWriteReq {
  "ws": string;
  "path": string;
  "d": Uint8Array;
  "mode"?: number;
  "append"?: boolean;
  "mkdirp"?: boolean;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface Finding {
  "severity": string;
  "check": string;
  "subject"?: string;
  "detail": string;
  "hint"?: string;
}

export interface FleetGetReq {
  "id": string;
}

export interface FleetListRes {
  "operations": Array<FleetOperation>;
}

export interface FleetOperation {
  "id": string;
  "selector": WorkspaceSelector;
  "action": string;
  "requested_by": string;
  "tenant": string;
  "state": string;
  "created_at": number;
  "deadline": number;
  "updated_at": number;
  "results": Array<FleetOperationResult>;
}

export interface FleetOperationResult {
  "workspace": string;
  "node"?: string;
  "backend"?: string;
  "generation"?: number;
  "state": string;
  "fenced"?: boolean;
  "acknowledged": boolean;
  "snapshot"?: string;
  "error"?: string;
  "updated_at": number;
}

export interface FleetQuarantineReq {
  "selector": WorkspaceSelector;
  "action": string;
  "deadline"?: number;
  "timeout_ms"?: number;
  "idem"?: string;
}

export interface Frame {
  "v": number;
  "t": string;
  "id"?: number;
  "seq"?: number;
  "s"?: string;
  "ws"?: string;
  "to"?: string;
  "from"?: string;
  "op"?: string;
  "body"?: Uint8Array;
  "err"?: Error | null;
}

export interface Gap {
  "from": number;
  "to": number;
}

export interface Grant {
  "claims": GrantClaims;
  "sig": Uint8Array;
  "node": string;
}

export interface GrantClaims {
  "client": string;
  "ws": string;
  "node": string;
  "principal"?: string;
  "tenant"?: string;
  "authz_revision"?: number;
  "exp": number;
  "gen": number;
}

export interface GrantReq {
  "ws": string;
}

export interface Hello {
  "peer": string;
  "role": string;
  "token"?: string;
  "caps"?: Array<string>;
  "pubkey"?: Uint8Array;
  "labels"?: Record<string, string>;
  "principal"?: string;
  "node"?: NodeInfo | null;
  "issued_at"?: number;
  "nonce"?: Uint8Array;
  "proof"?: Uint8Array;
}

export interface HelloOK {
  "peer": string;
  "caps": Array<string>;
  "server"?: string;
  "now": number;
  "pubkey"?: Uint8Array;
  "lease_sec"?: number;
  "subject"?: string;
  "tenant"?: string;
  "node_token"?: string;
}

export interface Idle {
  "snapshot_every_sec"?: number;
  "destroy_after_sec"?: number;
}

export interface NetworkPolicy {
  "default"?: string;
  "rules"?: Array<EgressRule>;
}

export interface NodeDiag {
  "node": string;
  "info": NodeInfo;
  "now": number;
  "uptime_sec": number;
  "data_dir": string;
  "disk_free_bytes": number;
  "disk_total_bytes": number;
  "goroutines": number;
  "heap_bytes": number;
  "workspaces"?: Array<WSDiag>;
  "artifacts": number;
  "artifact_bytes"?: number;
  "artifact_reserved_bytes"?: number;
  "artifact_reserved_objects"?: number;
  "artifact_max_bytes"?: number;
  "artifact_max_objects"?: number;
  "sessions_retained"?: number;
  "sessions_active"?: number;
  "sessions_max"?: number;
  "sessions_active_max"?: number;
  "sessions_per_workspace_max"?: number;
  "sessions_per_principal_max"?: number;
  "session_memory_bytes"?: number;
  "session_spill_bytes"?: number;
  "session_memory_chunks"?: number;
  "session_chunk_bytes"?: number;
  "requests_active_max"?: number;
  "connector_max_bytes"?: number;
  "connector_scope_max_bytes"?: number;
  "connector_object_max_bytes"?: number;
  "connector_max_objects"?: number;
  "connector_scope_max_objects"?: number;
  "mutation_records"?: number;
  "mutation_records_max"?: number;
  "snapshots_active"?: number;
  "snapshots_active_max"?: number;
  "metrics"?: Record<string, number>;
  "findings"?: Array<Finding>;
}

export interface NodeDiagReq {
  "ws"?: string;
  "grant"?: Grant | null;
  "verify"?: boolean;
}

export interface NodeInfo {
  "backends": Array<string>;
  "backend_descriptors"?: Array<BackendDescriptor>;
  "connectors"?: Array<string>;
  "os": string;
  "arch": string;
  "cpu": number;
  "mem_mib": number;
  "caps"?: Array<string>;
  "snapshots"?: string;
  "version"?: string;
}

export interface NodeListRes {
  "nodes": Array<NodeStatus>;
}

export interface NodeStatus {
  "id": string;
  "labels"?: Record<string, string>;
  "info": NodeInfo;
  "online": boolean;
  "last_seen": number;
  "workspaces"?: Array<string>;
  "protocol"?: Array<string>;
}

export interface Placement {
  "allow"?: Record<string, string>;
  "prefer"?: Record<string, string>;
  "node"?: string;
}

export interface Pool {
  "spec": PoolSpec;
  "tenant": string;
  "owner": string;
  "current": number;
  "created_at": number;
  "updated_at": number;
}

export interface PoolCreateReq {
  "spec": PoolSpec;
  "idem"?: string;
}

export interface PoolGetReq {
  "name": string;
}

export interface PoolListRes {
  "pools": Array<Pool>;
}

export interface PoolRemoveReq {
  "name": string;
  "idem"?: string;
}

export interface PoolSpec {
  "name": string;
  "vendor": string;
  "min": number;
  "max": number;
  "labels"?: Record<string, string>;
  "backend": string;
  "idle_scale_down_ms"?: number;
  "region"?: string;
  "size"?: string;
}

export interface PortOpenReq {
  "ws": string;
  "port": number;
  "host"?: string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface Queue {
  "id": string;
  "ws": string;
  "tenant": string;
  "owner": string;
  "recipe"?: string;
  "items": Array<QueueItem>;
  "cursor": number;
  "status": string;
  "sleep_after_sec"?: number;
  "sleep_until"?: string;
  "created_at": number;
  "updated_at": number;
}

export interface QueueAdvanceReq {
  "id": string;
  "index": number;
  "session"?: string;
  "exit": number;
  "signal"?: string;
  "idem"?: string;
}

export interface QueueCreateReq {
  "ws": string;
  "recipe"?: string;
  "tasks": Array<string>;
  "sleep_after_sec"?: number;
  "sleep_until"?: string;
  "idem"?: string;
}

export interface QueueGetReq {
  "id": string;
}

export interface QueueItem {
  "task": string;
  "session"?: string;
  "exit"?: number;
  "signal"?: string;
  "attempts"?: number;
  "finished_at"?: number;
}

export interface QueueListReq {
  "ws"?: string;
}

export interface QueueListRes {
  "queues": Array<Queue>;
}

export interface RepoSpec {
  "url"?: string;
  "ref"?: string;
  "depth"?: number;
  "branch"?: string;
}

export interface Requires {
  "cpu"?: number;
  "mem_mib"?: number;
  "backend"?: string;
  "caps"?: Array<string>;
  "os"?: string;
  "arch"?: string;
}

export interface RunInfo {
  "recipe": string;
  "task_hash"?: string;
  "sandbox"?: string;
  "auth"?: string;
}

export interface RuntimeCaps {
  "snapshots": string;
  "display"?: boolean;
  "mount_path"?: boolean;
}

export interface SAckReq {
  "s": string;
  "seq": number;
  "grant"?: Grant | null;
}

export interface SAttachReq {
  "s": string;
  "from": number;
  "grant"?: Grant | null;
}

export interface SCloseReq {
  "s": string;
  "kill"?: boolean;
  "grant"?: Grant | null;
}

export interface SInputReq {
  "s": string;
  "iseq": number;
  "d"?: Uint8Array;
  "eof"?: boolean;
  "grant"?: Grant | null;
}

export interface SListReq {
  "ws"?: string;
  "grant"?: Grant | null;
}

export interface SListRes {
  "sessions": Array<SessionStatus>;
}

export interface SOpenReq {
  "ws": string;
  "kind": string;
  "program": Array<string>;
  "cwd"?: string;
  "env"?: Record<string, string>;
  "rows"?: number;
  "cols"?: number;
  "stdin": boolean;
  "timeout_sec"?: number;
  "idem"?: string;
  "grant"?: Grant | null;
  "no_sub"?: boolean;
  "run"?: RunInfo | null;
}

export interface SOpenRes {
  "s": string;
  "next": number;
  "last_iseq"?: number;
}

export interface SResizeReq {
  "s": string;
  "rows": number;
  "cols": number;
  "grant"?: Grant | null;
}

export interface SSignalReq {
  "s": string;
  "signal": string;
  "grant"?: Grant | null;
}

export interface SWaitReq {
  "s": string;
  "timeout_sec"?: number;
  "grant"?: Grant | null;
}

export interface SWaitRes {
  "exited": boolean;
  "exit"?: ExitInfo | null;
}

export interface SecuritySpec {
  "profile"?: string;
  "min_isolation"?: string;
  "require_sibling_isolation"?: boolean;
  "require_enforced_egress"?: boolean;
  "secret_mode"?: string;
  "network"?: NetworkPolicy;
  "audit"?: AuditPolicy;
}

export interface SessionInfo {
  "id": string;
  "ws": string;
  "kind": string;
  "program"?: Array<string>;
  "pid"?: number;
  "opened_at": number;
  "run"?: RunInfo | null;
}

export interface SessionStatus {
  "info": SessionInfo;
  "exited": boolean;
  "exit"?: ExitInfo | null;
  "next": number;
  "oldest": number;
}

export interface Timer {
  "id": string;
  "ws": string;
  "at"?: number;
  "on"?: string;
  "action": string;
  "fired": boolean;
  "fired_at"?: number;
  "created_at": number;
}

export interface TimerListRes {
  "timers": Array<Timer>;
}

export interface TranscriptChunk {
  "seq": number;
  "stream": number;
  "at": number;
  "data": Uint8Array;
}

export interface TranscriptGap {
  "from": number;
  "to": number;
}

export interface TranscriptRecord {
  "index": number;
  "run": string;
  "seq": number;
  "stream": number;
  "at": number;
  "data": Uint8Array;
}

export interface Usage {
  "budget_id": string;
  "window": string;
  "since": number;
  "requests": number;
  "tokens": number;
  "estimated_cost_micros": number;
  "active_reservations": number;
  "unmetered_requests": number;
  "incomplete_requests": number;
}

export interface UsageReq {
  "tenant"?: string;
  "ws"?: string;
  "principal"?: string;
  "binding"?: string;
  "window"?: string;
}

export interface UsageRes {
  "usage": Array<Usage>;
}

export interface WSACLReq {
  "id": string;
  "acl": WorkspaceACL;
  "idem"?: string;
}

export interface WSClaimReq {
  "id": string;
}

export interface WSClaimRes {
  "workspace": Workspace;
  "lease_sec": number;
}

export interface WSCreateReq {
  "spec": WorkspaceSpec;
  "idem"?: string;
}

export interface WSDiag {
  "id": string;
  "gen": number;
  "backend": string;
  "root": string;
  "bytes": number;
  "files": number;
  "broker"?: string;
  "bindings"?: Array<string>;
  "lease_ends"?: number;
  "sessions"?: Array<SessionStatus>;
}

export interface WSGetReq {
  "id": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface WSInfoRes {
  "ws": string;
  "backend": string;
  "root"?: string;
  "sessions"?: Array<string>;
  "broker"?: string;
}

export interface WSListRes {
  "workspaces": Array<Workspace>;
}

export interface WSMoveReq {
  "id": string;
  "requires"?: Requires | null;
  "placement"?: Placement | null;
  "idem"?: string;
}

export interface WSQuarantineCommitReq {
  "operation": string;
  "ws": string;
  "gen": number;
  "backend": string;
  "snapshot": string;
}

export interface WSQuarantineReq {
  "operation": string;
  "ws": string;
  "gen": number;
  "action": string;
  "backend"?: string;
  "exclude"?: Array<string>;
  "security"?: SecuritySpec;
}

export interface WSQuarantineRes {
  "fenced": boolean;
  "gen": number;
  "action": string;
  "backend"?: string;
  "snapshot"?: string;
  "warning"?: string;
}

export interface WSReadyReq {
  "id": string;
  "gen": number;
}

export interface WSReleaseCommitReq {
  "id": string;
  "gen": number;
  "snapshot"?: string;
}

export interface WSReleaseReq {
  "ws": string;
  "gen": number;
  "snapshot": boolean;
  "reason"?: string;
}

export interface WSReleasedReq {
  "id": string;
  "gen": number;
  "snapshot"?: string;
  "reason"?: string;
  "failed"?: boolean;
  "preparing"?: boolean;
}

export interface WSRenewReq {
  "ids": Array<string>;
  "gen"?: Record<string, number>;
  "authz"?: Record<string, number>;
}

export interface WSRenewRes {
  "results": Array<WSRenewResult>;
}

export interface WSRenewResult {
  "id": string;
  "gen": number;
  "accepted": boolean;
  "authoritative_gen"?: number;
  "lease_until"?: number;
  "action": string;
  "authz_revision"?: number;
  "revoked"?: Array<string>;
  "authz_reset"?: boolean;
}

export interface WSSleepReq {
  "id": string;
  "after_sec"?: number;
  "at"?: number;
  "on"?: string;
  "idem"?: string;
}

export interface WSSnapshotCommitReq {
  "id": string;
  "gen": number;
  "snapshot": string;
}

export interface WSSnapshotReq {
  "ws": string;
  "upload": boolean;
  "authoritative"?: boolean;
  "idem"?: string;
  "grant"?: Grant | null;
  "gen"?: number;
}

export interface WSSnapshotRes {
  "artifact": string;
  "bytes": number;
  "consistency": string;
  "authoritative": boolean;
}

export interface Workspace {
  "id": string;
  "spec": WorkspaceSpec;
  "state": string;
  "node"?: string;
  "lease_until"?: number;
  "last_snapshot"?: string;
  "created_at": number;
  "updated_at": number;
  "gen": number;
  "tenant"?: string;
  "owner"?: string;
  "authz_revision"?: number;
  "revocations"?: Array<AuthzRevocation>;
  "revocation_floor"?: number;
  "quarantine_operation"?: string;
  "quarantined_at"?: number;
}

export interface WorkspaceACL {
  "readers"?: Array<string>;
  "writers"?: Array<string>;
}

export interface WorkspaceSelector {
  "all"?: boolean;
  "tenant"?: string;
  "principal"?: string;
  "run"?: string;
  "node"?: string;
  "model"?: string;
  "backend"?: string;
  "labels"?: Record<string, string>;
  "created_after"?: number;
  "created_before"?: number;
}

export interface WorkspaceSpec {
  "name"?: string;
  "run"?: string;
  "model"?: string;
  "labels"?: Record<string, string>;
  "image"?: string;
  "restore_from"?: string;
  "base"?: string;
  "requires": Requires;
  "placement": Placement;
  "bindings"?: Array<string>;
  "env"?: Record<string, string>;
  "principal"?: string;
  "idle": Idle;
  "exclude"?: Array<string>;
  "security"?: SecuritySpec;
  "acl"?: WorkspaceACL;
  "mount_path"?: string;
  "repo"?: RepoSpec;
}

export const OPERATIONS = {
  "agent.approval.decided": { constant: "OpAgentApprovalDecided", request: "AgentApprovalDecidedReq", response: "", mutating: false },
  "agent.cancel": { constant: "OpAgentCancel", request: "AgentGetReq", response: "Agent", mutating: true },
  "agent.create": { constant: "OpAgentCreate", request: "AgentCreateReq", response: "Agent", mutating: true },
  "agent.deliver": { constant: "OpAgentDeliver", request: "AgentDeliverReq", response: "", mutating: false },
  "agent.destroy": { constant: "OpAgentDestroy", request: "AgentGetReq", response: "", mutating: true },
  "agent.fork": { constant: "OpAgentFork", request: "AgentForkReq", response: "Agent", mutating: true },
  "agent.get": { constant: "OpAgentGet", request: "AgentGetReq", response: "Agent", mutating: false },
  "agent.list": { constant: "OpAgentList", request: "AgentListReq", response: "AgentListRes", mutating: false },
  "agent.message": { constant: "OpAgentMessage", request: "AgentMessageReq", response: "AgentMessageRes", mutating: true },
  "agent.report": { constant: "OpAgentReport", request: "AgentReport", response: "", mutating: false },
  "agent.run": { constant: "OpAgentRun", request: "AgentRunReq", response: "AgentRunRes", mutating: false },
  "agent.run.cancel": { constant: "OpAgentRunCancel", request: "AgentRunCancelReq", response: "", mutating: false },
  "agent.sleep": { constant: "OpAgentSleep", request: "AgentGetReq", response: "Agent", mutating: true },
  "agent.transcript": { constant: "OpAgentTranscript", request: "AgentTranscriptReq", response: "AgentTranscriptRes", mutating: false },
  "agent.wake": { constant: "OpAgentWake", request: "AgentWakeReq", response: "Agent", mutating: true },
  "approval.decide": { constant: "OpApprovalDecide", request: "ApprovalDecideReq", response: "Approval", mutating: true },
  "approval.get": { constant: "OpApprovalGet", request: "ApprovalGetReq", response: "Approval", mutating: false },
  "approval.list": { constant: "OpApprovalList", request: "ApprovalListReq", response: "ApprovalListRes", mutating: false },
  "base.create": { constant: "OpBaseCreate", request: "BaseCreateReq", response: "Base", mutating: true },
  "base.list": { constant: "OpBaseList", request: "", response: "BaseListRes", mutating: false },
  "base.remove": { constant: "OpBaseRemove", request: "BaseRemoveReq", response: "", mutating: true },
  "binding.lease": { constant: "OpBindingLease", request: "BindingLeaseReq", response: "BindingLeaseRes", mutating: false },
  "budget.create": { constant: "OpBudgetCreate", request: "BudgetCreateReq", response: "Budget", mutating: true },
  "budget.list": { constant: "OpBudgetList", request: "BudgetListReq", response: "BudgetListRes", mutating: false },
  "budget.remove": { constant: "OpBudgetRemove", request: "BudgetRemoveReq", response: "", mutating: true },
  "budget.reserve": { constant: "OpBudgetReserve", request: "BudgetReserveReq", response: "BudgetReservation", mutating: false },
  "budget.settle": { constant: "OpBudgetSettle", request: "BudgetSettleReq", response: "BudgetSettlement", mutating: false },
  "diag": { constant: "OpDiag", request: "DiagReq", response: "", mutating: false },
  "egress.approval": { constant: "OpEgressApproval", request: "EgressApprovalReq", response: "EgressApprovalRes", mutating: false },
  "events.post": { constant: "OpEventsPost", request: "EventPost", response: "", mutating: false },
  "events.stop": { constant: "OpEventsStop", request: "EventsStopReq", response: "", mutating: false },
  "events.tail": { constant: "OpEventsTail", request: "EventsTailReq", response: "", mutating: false },
  "fleet.get": { constant: "OpFleetGet", request: "FleetGetReq", response: "FleetOperation", mutating: false },
  "fleet.list": { constant: "OpFleetList", request: "", response: "FleetListRes", mutating: false },
  "fleet.quarantine": { constant: "OpFleetQuarantine", request: "FleetQuarantineReq", response: "FleetOperation", mutating: true },
  "fs.apply_tar": { constant: "OpFSApplyTar", request: "FSApplyTarReq", response: "FSApplyTarRes", mutating: true },
  "fs.edit": { constant: "OpFSEdit", request: "FSEditReq", response: "FSEditRes", mutating: true },
  "fs.list": { constant: "OpFSList", request: "FSListReq", response: "FSListRes", mutating: false },
  "fs.mkdir": { constant: "OpFSMkdir", request: "FSMkdirReq", response: "", mutating: true },
  "fs.read": { constant: "OpFSRead", request: "FSReadReq", response: "FSReadRes", mutating: false },
  "fs.remove": { constant: "OpFSRemove", request: "FSRemoveReq", response: "", mutating: true },
  "fs.rename": { constant: "OpFSRename", request: "FSRenameReq", response: "", mutating: true },
  "fs.search": { constant: "OpFSSearch", request: "FSSearchReq", response: "FSSearchRes", mutating: false },
  "fs.stat": { constant: "OpFSStat", request: "", response: "FSStatRes", mutating: false },
  "fs.write": { constant: "OpFSWrite", request: "FSWriteReq", response: "", mutating: true },
  "grant": { constant: "OpGrant", request: "GrantReq", response: "Grant", mutating: false },
  "node.diag": { constant: "OpNodeDiag", request: "NodeDiagReq", response: "", mutating: false },
  "node.list": { constant: "OpNodeList", request: "", response: "NodeListRes", mutating: false },
  "node.status": { constant: "OpNodeStatus", request: "", response: "", mutating: false },
  "pool.create": { constant: "OpPoolCreate", request: "PoolCreateReq", response: "Pool", mutating: true },
  "pool.get": { constant: "OpPoolGet", request: "PoolGetReq", response: "Pool", mutating: false },
  "pool.list": { constant: "OpPoolList", request: "", response: "PoolListRes", mutating: false },
  "pool.remove": { constant: "OpPoolRemove", request: "PoolRemoveReq", response: "", mutating: true },
  "port.open": { constant: "OpPortOpen", request: "PortOpenReq", response: "SOpenRes", mutating: true },
  "queue.advance": { constant: "OpQueueAdvance", request: "QueueAdvanceReq", response: "Queue", mutating: true },
  "queue.create": { constant: "OpQueueCreate", request: "QueueCreateReq", response: "Queue", mutating: true },
  "queue.get": { constant: "OpQueueGet", request: "QueueGetReq", response: "Queue", mutating: false },
  "queue.list": { constant: "OpQueueList", request: "QueueListReq", response: "QueueListRes", mutating: false },
  "s.ack": { constant: "OpSAck", request: "SAckReq", response: "", mutating: false },
  "s.attach": { constant: "OpSAttach", request: "SAttachReq", response: "SOpenRes", mutating: false },
  "s.close": { constant: "OpSClose", request: "SCloseReq", response: "", mutating: false },
  "s.input": { constant: "OpSInput", request: "SInputReq", response: "", mutating: false },
  "s.list": { constant: "OpSList", request: "SListReq", response: "SListRes", mutating: false },
  "s.open": { constant: "OpSOpen", request: "SOpenReq", response: "SOpenRes", mutating: true },
  "s.resize": { constant: "OpSResize", request: "SResizeReq", response: "", mutating: false },
  "s.signal": { constant: "OpSSignal", request: "SSignalReq", response: "", mutating: false },
  "s.wait": { constant: "OpSWait", request: "SWaitReq", response: "SWaitRes", mutating: false },
  "timer.list": { constant: "OpTimerList", request: "", response: "TimerListRes", mutating: false },
  "usage.get": { constant: "OpUsageGet", request: "UsageReq", response: "UsageRes", mutating: false },
  "ws.acl": { constant: "OpWSACL", request: "WSACLReq", response: "Workspace", mutating: true },
  "ws.claim": { constant: "OpWSClaim", request: "WSClaimReq", response: "WSClaimRes", mutating: false },
  "ws.create": { constant: "OpWSCreate", request: "WSCreateReq", response: "Workspace", mutating: true },
  "ws.destroy": { constant: "OpWSDestroy", request: "WSGetReq", response: "", mutating: true },
  "ws.get": { constant: "OpWSGet", request: "WSGetReq", response: "Workspace", mutating: false },
  "ws.info": { constant: "OpWSInfo", request: "WSGetReq", response: "WSInfoRes", mutating: false },
  "ws.list": { constant: "OpWSList", request: "", response: "WSListRes", mutating: false },
  "ws.move": { constant: "OpWSMove", request: "WSMoveReq", response: "Workspace", mutating: true },
  "ws.quarantine": { constant: "OpWSQuarantine", request: "WSQuarantineReq", response: "WSQuarantineRes", mutating: false },
  "ws.quarantine.commit": { constant: "OpWSQuarantineCommit", request: "WSQuarantineCommitReq", response: "", mutating: false },
  "ws.ready": { constant: "OpWSReady", request: "WSReadyReq", response: "", mutating: false },
  "ws.release": { constant: "OpWSRelease", request: "WSReleaseReq", response: "", mutating: false },
  "ws.release.abort": { constant: "OpWSReleaseAbort", request: "", response: "", mutating: false },
  "ws.release.commit": { constant: "OpWSReleaseCommit", request: "WSReleaseCommitReq", response: "", mutating: false },
  "ws.released": { constant: "OpWSReleased", request: "WSReleasedReq", response: "", mutating: false },
  "ws.renew": { constant: "OpWSRenew", request: "WSRenewReq", response: "WSRenewRes", mutating: false },
  "ws.sleep": { constant: "OpWSSleep", request: "WSSleepReq", response: "Timer", mutating: true },
  "ws.snapshot": { constant: "OpWSSnapshot", request: "WSSnapshotReq", response: "WSSnapshotRes", mutating: true },
  "ws.snapshot.commit": { constant: "OpWSSnapshotCommit", request: "WSSnapshotCommitReq", response: "", mutating: false },
  "ws.wake": { constant: "OpWSWake", request: "WSGetReq", response: "Workspace", mutating: true },
} as const;
