// Code generated by cmd/protogen; DO NOT EDIT.

export interface ACPCapabilities {
  "load_session"?: boolean;
  "resume_session"?: boolean;
  "close_session"?: boolean;
  "additional_directories"?: boolean;
}

export interface ACPFrameRecord {
  "at": number;
  "frame": unknown;
  "replayed"?: boolean;
  "redacted"?: boolean;
  "truncated"?: boolean;
}

export interface ACPRecordAssembler {
}

export interface Agent {
  "id": string;
  "tenant": string;
  "owner": string;
  "name"?: string;
  "ws": string;
  "owns_ws"?: boolean;
  "spec": AgentSpec;
  "mode": string;
  "acp_session_id"?: string;
  "capabilities"?: ACPCapabilities | null;
  "status": string;
  "status_reason"?: string;
  "inbox": Array<AgentMessage>;
  "runs": Array<AgentRun>;
  "turns": number;
  "parent"?: string;
  "forked_from"?: string;
  "policy": AgentPolicy;
  "transcript_session"?: string;
  "transcript_node"?: string;
  "transcript_next"?: number;
  "transcript_first"?: number;
  "transcript_bytes"?: number;
  "pending_approvals"?: number;
  "url"?: string;
  "created_at": number;
  "updated_at": number;
  "wake_timer"?: string;
  "idle_since"?: number;
  "failures"?: number;
  "parent_notified"?: boolean;
}

export interface AgentApprovalDecidedReq {
  "agent": string;
  "run": string;
  "approval": string;
  "decision": ApprovalDecision;
}

export interface AgentCreateReq {
  "name"?: string;
  "ws"?: string;
  "workspace"?: WorkspaceSpec | null;
  "spec": AgentSpec;
  "policy": AgentPolicy;
  "parent"?: string;
  "acp_session_id"?: string;
  "idem"?: string;
}

export interface AgentDeliverReq {
  "agent": string;
  "run": string;
  "message": AgentMessage;
}

export interface AgentForkReq {
  "id": string;
  "name"?: string;
  "task"?: string;
  "policy"?: AgentPolicy | null;
  "idem"?: string;
}

export interface AgentGetReq {
  "id": string;
  "idem"?: string;
}

export interface AgentListReq {
  "status"?: string;
  "ws"?: string;
  "parent"?: string;
}

export interface AgentListRes {
  "agents": Array<Agent>;
}

export interface AgentMessage {
  "id": string;
  "kind": string;
  "text": string;
  "by"?: string;
  "at": number;
}

export interface AgentMessageReq {
  "id": string;
  "text": string;
  "kind"?: string;
  "idem"?: string;
}

export interface AgentMessageRes {
  "agent": Agent;
  "message": AgentMessage;
  "degraded"?: boolean;
  "woken"?: boolean;
}

export interface AgentPolicy {
  "sleep_after_sec"?: number;
  "approve"?: string;
  "max_turns"?: number;
  "start_at"?: number;
}

export interface AgentReport {
  "agent": string;
  "run": string;
  "ws": string;
  "gen": number;
  "seq": number;
  "kind": string;
  "at": number;
  "transcript"?: string;
  "acp_session_id"?: string;
  "capabilities"?: ACPCapabilities | null;
  "loaded"?: boolean;
  "message"?: string;
  "stop_reason"?: string;
  "error"?: string;
  "exit_code"?: number;
  "cancelled"?: boolean;
  "tool_call"?: string;
  "tool_kind"?: string;
  "tool_title"?: string;
  "tool_status"?: string;
  "locations"?: Array<string>;
  "approval"?: Approval | null;
  "usage"?: AgentUsage | null;
  "chunks"?: Array<TranscriptChunk>;
}

export interface AgentRun {
  "id": string;
  "attempt": number;
  "node"?: string;
  "gen"?: number;
  "state": string;
  "transcript"?: string;
  "loaded"?: boolean;
  "started_at"?: number;
  "finished_at"?: number;
  "stop_reason"?: string;
  "error"?: string;
  "turns": number;
  "last_report"?: number;
  "turn_message"?: string;
}

export interface AgentRunCancelReq {
  "agent": string;
  "run": string;
  "reason"?: string;
}

export interface AgentRunReq {
  "agent": string;
  "run": string;
  "attempt": number;
  "ws": string;
  "gen": number;
  "tenant": string;
  "owner": string;
  "spec": AgentSpec;
  "policy": AgentPolicy;
  "mode": string;
  "acp_session_id"?: string;
  "messages": Array<AgentMessage>;
}

export interface AgentRunRes {
  "transcript": string;
}

export interface AgentSpec {
  "recipe": string;
  "recipe_yaml"?: string;
  "task": string;
  "providers"?: Array<string>;
  "primary"?: string;
  "binding_specs"?: Array<string>;
  "model"?: string;
  "sandbox"?: string;
  "acp_command"?: Array<string>;
  "auth"?: string;
  "mode"?: string;
}

export interface AgentTranscriptReq {
  "id": string;
  "from"?: number;
  "limit"?: number;
}

export interface AgentTranscriptRes {
  "records": Array<TranscriptRecord>;
  "next": number;
  "gap"?: TranscriptGap | null;
  "done"?: boolean;
}

export interface AgentUsage {
  "input"?: number;
  "output"?: number;
}

export interface AgentWakeReq {
  "id": string;
  "by"?: string;
  "idem"?: string;
}

export interface Approval {
  "id": string;
  "tenant": string;
  "owner": string;
  "agent"?: string;
  "ws"?: string;
  "run"?: string;
  "principal"?: string;
  "rule"?: string;
  "host"?: string;
  "method"?: string;
  "path_hash"?: string;
  "body_hash"?: string;
  "fingerprint"?: string;
  "kind": string;
  "title"?: string;
  "tool_call"?: string;
  "tool_kind"?: string;
  "locations"?: Array<string>;
  "options"?: Array<ApprovalOption>;
  "detail"?: unknown;
  "status": string;
  "decision"?: ApprovalDecision | null;
  "delivered_at"?: number;
  "created_at": number;
  "updated_at": number;
  "expires_at"?: number;
}

export interface ApprovalDecideReq {
  "id": string;
  "option"?: string;
  "denied"?: boolean;
  "content"?: unknown;
  "remember"?: string;
  "idem"?: string;
}

export interface ApprovalDecision {
  "option"?: string;
  "denied"?: boolean;
  "content"?: unknown;
  "by": string;
  "at": number;
  "remember"?: string;
}

export interface ApprovalGetReq {
  "id": string;
}

export interface ApprovalListReq {
  "agent"?: string;
  "kind"?: string;
  "status"?: string;
}

export interface ApprovalListRes {
  "approvals": Array<Approval>;
}

export interface ApprovalOption {
  "id": string;
  "name"?: string;
  "kind"?: string;
}

export interface ArtifactProofClaims {
  "id": string;
  "node": string;
  "tenant": string;
  "ws": string;
  "gen": number;
  "method": string;
  "artifact": string;
  "issued_at": number;
  "expires_at": number;
}

export interface ArtifactProofEnvelope {
  "claims": ArtifactProofClaims;
  "signature": Uint8Array;
}

export interface ArtifactProofReq {
  "ws": string;
  "gen": number;
  "method": string;
  "artifact": string;
}

export interface ArtifactProofRes {
  "proof": string;
}

export interface AuditExportReq {
  "tenant"?: string;
  "from": number;
  "to": number;
}

export interface AuditExportRes {
  "manifest": AuditManifest;
  "signature": string;
  "bundle": Uint8Array;
}

export interface AuditKeyReq {
}

export interface AuditKeyRes {
  "key_id": string;
  "algorithm": string;
  "public_key": string;
}

export interface AuditManifest {
  "schema": string;
  "tenant": string;
  "range_from": number;
  "range_to": number;
  "created_at": number;
  "event_count": number;
  "first_seq"?: number;
  "last_seq"?: number;
  "payload_bytes": number;
  "payload_sha256": string;
  "hash_algorithm": string;
  "signature_algorithm": string;
  "key_id": string;
}

export interface AuditPolicy {
  "required"?: boolean;
}

export interface AuthzRevocation {
  "rev": number;
  "principal": string;
}

export interface BackendDescriptor {
  "name": string;
  "security": BackendSecurityCaps;
  "runtime": RuntimeCaps;
}

export interface BackendSecurityCaps {
  "isolation": string;
  "multi_tenant": boolean;
  "sibling_isolation": boolean;
  "egress_mode": string;
  "broker_identity": string;
  "filesystem_boundary": string;
  "network_namespace": boolean;
  "device_isolation": boolean;
}

export interface Base {
  "name": string;
  "tenant": string;
  "owner": string;
  "artifact": string;
  "format"?: string;
  "objects"?: Array<string>;
  "workspace"?: string;
  "bytes"?: number;
  "created_at": number;
}

export interface BaseCreateReq {
  "name": string;
  "artifact": string;
  "format"?: string;
  "workspace"?: string;
  "idem"?: string;
}

export interface BaseListRes {
  "bases": Array<Base>;
}

export interface BaseRemoveReq {
  "name": string;
  "idem"?: string;
}

export interface BindingLease {
  "id": string;
  "secret": string;
  "destinations": Array<string>;
  "shape"?: string;
  "principals"?: Array<string>;
  "expires_at": number;
  "placeholder"?: string;
}

export interface BindingLeaseReq {
  "ws": string;
  "gen"?: number;
}

export interface BindingLeaseRes {
  "leases": Array<BindingLease>;
}

export interface Budget {
  "id": string;
  "tenant"?: string;
  "attach_to": string;
  "attach_id": string;
  "window": string;
  "max_requests"?: number;
  "max_tokens"?: number;
  "max_estimated_cost_micros"?: number;
  "created_at"?: number;
  "updated_at"?: number;
}

export interface BudgetCreateReq {
  "budget": Budget;
  "idem"?: string;
}

export interface BudgetListReq {
}

export interface BudgetListRes {
  "budgets": Array<Budget>;
}

export interface BudgetRemoveReq {
  "id": string;
  "idem"?: string;
}

export interface BudgetReservation {
  "id"?: string;
  "tracked"?: boolean;
  "budget_ids"?: Array<string>;
  "unmetered_reason"?: string;
  "expires_at"?: number;
  "denied"?: boolean;
  "limit"?: string;
}

export interface BudgetReserveReq {
  "key": string;
  "ws": string;
  "gen": number;
  "principal"?: string;
  "bindings"?: Array<string>;
  "provider": string;
  "model"?: string;
  "input_tokens"?: number;
  "max_output_tokens"?: number;
  "metered"?: boolean;
}

export interface BudgetSettleReq {
  "reservation": string;
  "mode": string;
  "input_tokens"?: number;
  "output_tokens"?: number;
}

export interface BudgetSettlement {
  "reservation": string;
  "mode": string;
  "tokens"?: number;
  "estimated_cost_micros"?: number;
  "estimated_cost_unavailable"?: boolean;
  "usage_exceeded_reservation"?: boolean;
}

export interface ChildSummary {
  "child": string;
  "name"?: string;
  "status": string;
  "reason"?: string;
  "turns": number;
  "ws": string;
  "url"?: string;
}

export interface ChunkBody {
  "st": number;
  "d"?: Uint8Array;
}

export interface ComputerAction {
  "kind": string;
  "x"?: number;
  "y"?: number;
  "dx"?: number;
  "dy"?: number;
  "tox"?: number;
  "toy"?: number;
  "text"?: string;
  "key"?: string;
  "button"?: string;
  "mod"?: number;
}

export interface ComputerCloseReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
  "idem"?: string;
}

export interface ComputerCreateReq {
  "ws": string;
  "idem"?: string;
  "grant"?: Grant | null;
  "launch"?: ComputerLaunch | null;
  "viewport"?: ComputerViewport;
  "profile"?: string;
  "env"?: Record<string, string>;
}

export interface ComputerCreateRes {
  "computer": string;
  "s"?: string;
  "cdp"?: string;
  "viewport"?: ComputerViewport;
}

export interface ComputerDownload {
  "artifact"?: string;
  "filename"?: string;
  "url"?: string;
  "bytes"?: number;
  "state": string;
  "reason"?: string;
}

export interface ComputerDownloadsReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
}

export interface ComputerDownloadsRes {
  "downloads"?: Array<ComputerDownload>;
}

export interface ComputerEvalReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
  "expr": string;
}

export interface ComputerEvalRes {
  "value"?: Uint8Array;
}

export interface ComputerGetReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
}

export interface ComputerGetRes {
  "computer": string;
  "state": string;
  "reason"?: string;
  "viewport"?: ComputerViewport;
  "s"?: string;
  "last_iseq"?: number;
}

export interface ComputerInputReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
  "iseq": number;
  "actions"?: Array<ComputerAction>;
}

export interface ComputerInputRes {
  "applied": boolean;
  "last_iseq": number;
}

export interface ComputerLaunch {
  "program"?: Array<string>;
  "port"?: number;
  "attach"?: boolean;
}

export interface ComputerNavigateReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
  "url": string;
  "idem"?: string;
}

export interface ComputerNavigateRes {
  "url"?: string;
  "title"?: string;
  "status"?: string;
}

export interface ComputerScreenshotReq {
  "ws": string;
  "computer": string;
  "grant"?: Grant | null;
}

export interface ComputerScreenshotRes {
  "png": Uint8Array;
  "w": number;
  "h": number;
}

export interface ComputerViewport {
  "w"?: number;
  "h"?: number;
}

export interface ControlDiag {
  "now": number;
  "uptime_sec": number;
  "version"?: string;
  "ws_state": Record<string, number>;
  "nodes_total": number;
  "nodes_online": number;
  "timers_pending": number;
  "timers_fired": number;
  "timers_max"?: number;
  "mutation_records"?: number;
  "mutation_records_max"?: number;
  "event_seq": number;
  "event_oldest"?: number;
  "events_max"?: number;
  "requests_active_max"?: number;
  "bindings"?: Array<string>;
  "artifact_count": number;
  "artifact_bytes": number;
  "artifact_reserved_bytes"?: number;
  "artifact_reserved_objects"?: number;
  "artifact_max_bytes"?: number;
  "artifact_max_objects"?: number;
  "workspaces_per_tenant_max"?: number;
  "workspaces_per_subject_max"?: number;
  "db_integrity"?: string;
  "lease_sec": number;
  "controller_role"?: string;
  "controller_epoch"?: number;
  "controller_lease_age_ms"?: number;
  "last_replicated_at"?: number;
  "restored_event_seq"?: number;
  "recovery_lost_window_ms"?: number;
  "controller_reconciling"?: boolean;
  "metrics"?: Record<string, number>;
  "findings"?: Array<Finding>;
}

export interface ControllerNodeState {
  "node": string;
  "epoch": number;
  "workspaces"?: Array<ControllerWorkspace>;
  "releases"?: Array<ControllerReleaseState>;
}

export interface ControllerReleaseState {
  "request": WSReleaseReq;
  "response": WSReleasedReq;
  "operation_id"?: string;
  "state": string;
}

export interface ControllerWorkspace {
  "workspace": Workspace;
  "sessions"?: Array<string>;
}

export interface DiagReq {
  "verify"?: boolean;
}

export interface E2EEKeyExchange {
  "type": string;
  "suite"?: string;
  "caps"?: Array<string>;
  "session": Uint8Array;
  "from": string;
  "to": string;
  "eph"?: Uint8Array;
  "nonce"?: Uint8Array;
  "ts"?: number;
  "binding"?: PeerBinding;
  "sig"?: Uint8Array;
  "reason"?: string;
}

export interface E2EEPayload {
  "op"?: string;
  "s"?: string;
  "ws"?: string;
  "seq"?: number;
  "body"?: Uint8Array;
  "err"?: Error | null;
}

export interface E2EESealed {
  "sid": Uint8Array;
  "n": number;
  "ct": Uint8Array;
}

export interface EgressApprovalReq {
  "ws": string;
  "gen": number;
  "principal": string;
  "rule": string;
  "host": string;
  "method": string;
  "path_hash": string;
  "body_hash": string;
  "fingerprint": string;
  "wait_ms"?: number;
}

export interface EgressApprovalRes {
  "id": string;
  "status": string;
  "allowed"?: boolean;
  "expires_at"?: number;
}

export interface EgressRule {
  "id": string;
  "mode"?: string;
  "connector"?: string;
  "protocol": string;
  "hosts"?: Array<string>;
  "ports"?: Array<number>;
  "methods"?: Array<string>;
  "path_prefixes"?: Array<string>;
  "max_requests"?: number;
  "max_request_bytes"?: number;
  "max_response_bytes"?: number;
  "redact"?: Array<string>;
  "shared_state"?: string;
  "repos"?: Array<string>;
  "push"?: boolean;
}

export interface Error {
  "code": string;
  "msg"?: string;
  "oldest"?: number;
  "reason"?: string;
}

export interface Event {
  "seq": number;
  "at": number;
  "stream"?: string;
  "principal"?: string;
  "node"?: string;
  "event_id"?: string;
  "received_at"?: number;
  "observed_at"?: number;
  "origin"?: string;
  "actor"?: string;
  "tenant"?: string;
  "workspace"?: string;
  "generation"?: number;
  "controller_epoch"?: number;
  "session"?: string;
  "operation_id"?: string;
  "producer_seq"?: number;
  "type": string;
  "payload"?: Uint8Array;
  "cause"?: number;
}

export interface EventPost {
  "events": Array<Event>;
  "sub"?: string;
}

export interface EventsStopReq {
  "sub"?: string;
}

export interface EventsTailReq {
  "from": number;
  "follow": boolean;
  "ws"?: string;
  "sub"?: string;
}

export interface ExitInfo {
  "code": number;
  "signal"?: string;
  "error"?: string;
  "reason"?: string;
}

export interface FSApplyTarReq {
  "ws": string;
  "artifact": string;
  "path"?: string;
  "format"?: string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSApplyTarRes {
  "files": number;
  "dirs": number;
  "bytes": number;
}

export interface FSEdit {
  "old": string;
  "new": string;
  "all"?: boolean;
}

export interface FSEditReq {
  "ws": string;
  "path": string;
  "edits": Array<FSEdit>;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSEditRes {
  "replacements": number;
}

export interface FSEntry {
  "name": string;
  "size": number;
  "mode": number;
  "dir": boolean;
  "mtime": number;
  "link"?: boolean;
}

export interface FSListReq {
  "ws": string;
  "path": string;
  "grant"?: Grant | null;
}

export interface FSListRes {
  "entries": Array<FSEntry>;
}

export interface FSMatch {
  "path": string;
  "line": number;
  "text": string;
}

export interface FSMkdirReq {
  "ws": string;
  "path": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSReadReq {
  "ws": string;
  "path": string;
  "offset"?: number;
  "limit"?: number;
  "grant"?: Grant | null;
}

export interface FSReadRes {
  "d": Uint8Array;
  "size": number;
  "eof": boolean;
}

export interface FSRemoveReq {
  "ws": string;
  "path": string;
  "recursive"?: boolean;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSRenameReq {
  "ws": string;
  "from": string;
  "to": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface FSSearchReq {
  "ws": string;
  "path": string;
  "pattern": string;
  "glob"?: string;
  "max"?: number;
  "grant"?: Grant | null;
}

export interface FSSearchRes {
  "matches": Array<FSMatch>;
  "truncated": boolean;
}

export interface FSStatRes {
  "entry": FSEntry;
}

export interface FSWriteReq {
  "ws": string;
  "path": string;
  "d": Uint8Array;
  "mode"?: number;
  "append"?: boolean;
  "mkdirp"?: boolean;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface Finding {
  "severity": string;
  "check": string;
  "subject"?: string;
  "detail": string;
  "hint"?: string;
}

export interface FleetGetReq {
  "id": string;
}

export interface FleetListRes {
  "operations": Array<FleetOperation>;
}

export interface FleetOperation {
  "id": string;
  "selector": WorkspaceSelector;
  "action": string;
  "requested_by": string;
  "tenant": string;
  "state": string;
  "created_at": number;
  "deadline": number;
  "updated_at": number;
  "results": Array<FleetOperationResult>;
}

export interface FleetOperationResult {
  "workspace": string;
  "node"?: string;
  "backend"?: string;
  "generation"?: number;
  "state": string;
  "fenced"?: boolean;
  "acknowledged": boolean;
  "snapshot"?: string;
  "snapshot_format"?: string;
  "snapshot_objects"?: Array<string>;
  "error"?: string;
  "updated_at": number;
}

export interface FleetQuarantineReq {
  "selector": WorkspaceSelector;
  "action": string;
  "deadline"?: number;
  "timeout_ms"?: number;
  "idem"?: string;
}

export interface Frame {
  "v": number;
  "t": string;
  "controller_epoch"?: number;
  "id"?: number;
  "seq"?: number;
  "s"?: string;
  "ws"?: string;
  "to"?: string;
  "from"?: string;
  "op"?: string;
  "body"?: Uint8Array;
  "err"?: Error | null;
}

export interface Gap {
  "from": number;
  "to": number;
  "tier"?: string;
}

export interface Grant {
  "claims": GrantClaims;
  "sig": Uint8Array;
  "node": string;
}

export interface GrantClaims {
  "client": string;
  "ws": string;
  "node": string;
  "principal"?: string;
  "tenant"?: string;
  "roles"?: Array<string>;
  "authz_revision"?: number;
  "exp": number;
  "gen": number;
  "controller_epoch"?: number;
}

export interface GrantReq {
  "ws": string;
}

export interface Hello {
  "peer": string;
  "role": string;
  "token"?: string;
  "caps"?: Array<string>;
  "pubkey"?: Uint8Array;
  "labels"?: Record<string, string>;
  "principal"?: string;
  "node"?: NodeInfo | null;
  "issued_at"?: number;
  "nonce"?: Uint8Array;
  "proof"?: Uint8Array;
}

export interface HelloOK {
  "peer": string;
  "caps": Array<string>;
  "server"?: string;
  "now": number;
  "pubkey"?: Uint8Array;
  "lease_sec"?: number;
  "controller_epoch"?: number;
  "subject"?: string;
  "tenant"?: string;
  "node_token"?: string;
}

export interface Idle {
  "snapshot_every_sec"?: number;
  "destroy_after_sec"?: number;
}

export interface NetworkPolicy {
  "default"?: string;
  "rules"?: Array<EgressRule>;
}

export interface NodeDiag {
  "node": string;
  "controller_epoch"?: number;
  "info": NodeInfo;
  "now": number;
  "uptime_sec": number;
  "data_dir": string;
  "disk_free_bytes": number;
  "disk_total_bytes": number;
  "goroutines": number;
  "heap_bytes": number;
  "workspaces"?: Array<WSDiag>;
  "artifacts": number;
  "artifact_bytes"?: number;
  "artifact_reserved_bytes"?: number;
  "artifact_reserved_objects"?: number;
  "artifact_max_bytes"?: number;
  "artifact_max_objects"?: number;
  "sessions_retained"?: number;
  "sessions_active"?: number;
  "sessions_max"?: number;
  "sessions_active_max"?: number;
  "sessions_per_workspace_max"?: number;
  "sessions_per_principal_max"?: number;
  "session_memory_bytes"?: number;
  "session_spill_bytes"?: number;
  "session_memory_chunks"?: number;
  "session_chunk_bytes"?: number;
  "requests_active_max"?: number;
  "connector_max_bytes"?: number;
  "connector_scope_max_bytes"?: number;
  "connector_object_max_bytes"?: number;
  "connector_max_objects"?: number;
  "connector_scope_max_objects"?: number;
  "mutation_records"?: number;
  "mutation_records_max"?: number;
  "snapshots_active"?: number;
  "snapshots_active_max"?: number;
  "volumes"?: number;
  "volume_attachments"?: number;
  "volume_source_bytes"?: number;
  "volume_source_max_bytes"?: number;
  "volume_source_entries"?: number;
  "volume_source_max_entries"?: number;
  "volume_quota_rejections"?: number;
  "metrics"?: Record<string, number>;
  "findings"?: Array<Finding>;
}

export interface NodeDiagReq {
  "ws"?: string;
  "grant"?: Grant | null;
  "verify"?: boolean;
}

export interface NodeInfo {
  "backends": Array<string>;
  "backend_descriptors"?: Array<BackendDescriptor>;
  "connectors"?: Array<string>;
  "os": string;
  "arch": string;
  "cpu": number;
  "mem_mib": number;
  "caps"?: Array<string>;
  "snapshots"?: string;
  "version"?: string;
}

export interface NodeListRes {
  "nodes": Array<NodeStatus>;
}

export interface NodeStatus {
  "id": string;
  "labels"?: Record<string, string>;
  "info": NodeInfo;
  "online": boolean;
  "last_seen": number;
  "workspaces"?: Array<string>;
  "protocol"?: Array<string>;
}

export interface PeerBinding {
  "peer": string;
  "key": Uint8Array;
  "tenant"?: string;
  "issued"?: number;
  "exp": number;
  "sig"?: Uint8Array;
}

export interface Placement {
  "allow"?: Record<string, string>;
  "prefer"?: Record<string, string>;
  "node"?: string;
}

export interface Pool {
  "spec": PoolSpec;
  "tenant": string;
  "owner": string;
  "current": number;
  "created_at": number;
  "updated_at": number;
}

export interface PoolCreateReq {
  "spec": PoolSpec;
  "idem"?: string;
}

export interface PoolGetReq {
  "name": string;
}

export interface PoolListRes {
  "pools": Array<Pool>;
}

export interface PoolRemoveReq {
  "name": string;
  "idem"?: string;
}

export interface PoolSpec {
  "name": string;
  "vendor": string;
  "min": number;
  "max": number;
  "labels"?: Record<string, string>;
  "backend": string;
  "idle_scale_down_ms"?: number;
  "region"?: string;
  "size"?: string;
}

export interface PortOpenReq {
  "ws": string;
  "port": number;
  "host"?: string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface Principal {
  "id": string;
  "tenant": string;
  "roles": Array<string>;
  "revision": number;
  "created_at": number;
  "updated_at": number;
}

export interface PrincipalCreateReq {
  "tenant"?: string;
  "principal": string;
  "roles": Array<string>;
  "idem": string;
}

export interface PrincipalInviteReq {
  "tenant": string;
  "principal": string;
  "ttl_ms": number;
  "idem": string;
}

export interface PrincipalListReq {
  "tenant"?: string;
}

export interface PrincipalListRes {
  "principals": Array<Principal>;
}

export interface PrincipalRevokeReq {
  "tenant"?: string;
  "principal": string;
  "idem": string;
}

export interface PrincipalRevokeRes {
  "revision": number;
}

export interface PrincipalTokenIssueReq {
  "tenant"?: string;
  "principal": string;
  "role": string;
  "ttl_ms": number;
  "idem": string;
}

export interface PrincipalTokenIssueRes {
  "access_token": string;
  "expires_at": number;
}

export interface Queue {
  "id": string;
  "ws": string;
  "tenant": string;
  "owner": string;
  "recipe"?: string;
  "items": Array<QueueItem>;
  "cursor": number;
  "status": string;
  "sleep_after_sec"?: number;
  "sleep_until"?: string;
  "created_at": number;
  "updated_at": number;
}

export interface QueueAdvanceReq {
  "id": string;
  "index": number;
  "session"?: string;
  "exit": number;
  "signal"?: string;
  "idem"?: string;
}

export interface QueueCreateReq {
  "ws": string;
  "recipe"?: string;
  "tasks": Array<string>;
  "sleep_after_sec"?: number;
  "sleep_until"?: string;
  "idem"?: string;
}

export interface QueueGetReq {
  "id": string;
}

export interface QueueItem {
  "task": string;
  "session"?: string;
  "exit"?: number;
  "signal"?: string;
  "attempts"?: number;
  "finished_at"?: number;
}

export interface QueueListReq {
  "ws"?: string;
}

export interface QueueListRes {
  "queues": Array<Queue>;
}

export interface RepoSpec {
  "url"?: string;
  "ref"?: string;
  "depth"?: number;
  "branch"?: string;
}

export interface Requires {
  "cpu"?: number;
  "mem_mib"?: number;
  "backend"?: string;
  "caps"?: Array<string>;
  "os"?: string;
  "arch"?: string;
}

export interface RunInfo {
  "recipe": string;
  "task_hash"?: string;
  "sandbox"?: string;
  "auth"?: string;
}

export interface RuntimeCaps {
  "snapshots": string;
  "display"?: boolean;
  "mount_path"?: boolean;
}

export interface SAckReq {
  "s": string;
  "seq": number;
  "grant"?: Grant | null;
}

export interface SAttachReq {
  "s": string;
  "from": number;
  "subscription"?: string;
  "grant"?: Grant | null;
}

export interface SCloseReq {
  "s": string;
  "kill"?: boolean;
  "subscription"?: string;
  "grant"?: Grant | null;
}

export interface SInputReq {
  "s": string;
  "iseq": number;
  "d"?: Uint8Array;
  "eof"?: boolean;
  "grant"?: Grant | null;
}

export interface SListReq {
  "ws"?: string;
  "grant"?: Grant | null;
}

export interface SListRes {
  "sessions": Array<SessionStatus>;
}

export interface SOpenReq {
  "ws": string;
  "kind": string;
  "program": Array<string>;
  "cwd"?: string;
  "env"?: Record<string, string>;
  "rows"?: number;
  "cols"?: number;
  "stdin": boolean;
  "timeout_sec"?: number;
  "idem"?: string;
  "grant"?: Grant | null;
  "no_sub"?: boolean;
  "run"?: RunInfo | null;
}

export interface SOpenRes {
  "s": string;
  "next": number;
  "last_iseq"?: number;
}

export interface SResizeReq {
  "s": string;
  "rows": number;
  "cols": number;
  "grant"?: Grant | null;
}

export interface SSignalReq {
  "s": string;
  "signal": string;
  "grant"?: Grant | null;
}

export interface SWaitReq {
  "s": string;
  "timeout_sec"?: number;
  "grant"?: Grant | null;
}

export interface SWaitRes {
  "exited": boolean;
  "exit"?: ExitInfo | null;
}

export interface SecuritySpec {
  "profile"?: string;
  "min_isolation"?: string;
  "require_sibling_isolation"?: boolean;
  "require_enforced_egress"?: boolean;
  "secret_mode"?: string;
  "network"?: NetworkPolicy;
  "audit"?: AuditPolicy;
}

export interface SessionCapabilityCheckReq {
  "ws": string;
  "gen": number;
  "capability": string;
}

export interface SessionCapabilityCheckRes {
  "principal": string;
  "tenant": string;
}

export interface SessionCapabilityIssueReq {
  "client": string;
  "ws": string;
  "gen": number;
  "authz_revision": number;
  "principal": string;
  "tenant": string;
  "roles"?: Array<string>;
}

export interface SessionCapabilityIssueRes {
  "capability": string;
  "expires_at": number;
}

export interface SessionCapabilityRenewReq {
  "ws": string;
  "gen": number;
  "capability": string;
}

export interface SessionInfo {
  "id": string;
  "ws": string;
  "kind": string;
  "program"?: Array<string>;
  "pid"?: number;
  "opened_at": number;
  "run"?: RunInfo | null;
}

export interface SessionLogCommitReq {
  "session": string;
  "workspace": string;
  "gen": number;
  "principal": string;
  "kind": string;
  "info"?: SessionInfo;
  "exit"?: ExitInfo;
  "max_chunk": number;
  "segments"?: Array<SessionLogSegment>;
  "complete"?: boolean;
}

export interface SessionLogGetReq {
  "session": string;
  "workspace": string;
  "gen": number;
}

export interface SessionLogRecord {
  "session": string;
  "workspace": string;
  "tenant": string;
  "principal": string;
  "kind": string;
  "info": SessionInfo;
  "exit": ExitInfo;
  "max_chunk": number;
  "segments"?: Array<SessionLogSegment>;
  "complete"?: boolean;
  "updated_at": number;
  "expires_at"?: number;
}

export interface SessionLogSegment {
  "first": number;
  "next": number;
  "artifact": string;
  "bytes": number;
}

export interface SessionStatus {
  "info": SessionInfo;
  "exited": boolean;
  "exit"?: ExitInfo | null;
  "next": number;
  "oldest": number;
  "blob_bytes"?: number;
  "blob_segments"?: number;
  "unavailable_tier"?: string;
}

export interface Tenant {
  "id": string;
  "state": string;
  "revision": number;
  "policy": TenantPolicy;
  "created_at": number;
  "updated_at": number;
}

export interface TenantCreateReq {
  "id": string;
  "policy": TenantPolicy;
  "idem": string;
}

export interface TenantGetReq {
  "id": string;
}

export interface TenantListRes {
  "tenants": Array<Tenant>;
}

export interface TenantOIDC {
  "issuer"?: string;
  "client_id"?: string;
  "audience"?: string;
  "scopes"?: Array<string>;
  "group_roles"?: Record<string, Array<string>>;
  "tenant_claim"?: string;
  "groups_claim"?: string;
}

export interface TenantPolicy {
  "quotas": TenantQuotas;
  "retention": TenantRetention;
  "residency": TenantResidency;
  "oidc": TenantOIDC;
  "stripe_customer_id"?: string;
}

export interface TenantQuotas {
  "max_workspaces": number;
  "max_nodes": number;
  "max_artifact_bytes": number;
  "max_active_sessions": number;
}

export interface TenantResidency {
  "allowed_regions"?: Array<string>;
  "required_labels"?: Record<string, string>;
}

export interface TenantRetention {
  "events_ms": number;
  "session_logs_ms": number;
  "artifacts_ms": number;
  "meter_events_ms": number;
}

export interface TenantStateReq {
  "id": string;
  "state": string;
  "expected_revision": number;
  "idem": string;
}

export interface TenantUpdateReq {
  "id": string;
  "policy": TenantPolicy;
  "expected_revision": number;
  "idem": string;
}

export interface TenantUsage {
  "workspaces": number;
  "nodes": number;
  "artifact_bytes": number;
  "active_sessions": number;
}

export interface TenantUsageReq {
  "tenant"?: string;
}

export interface Timer {
  "id": string;
  "ws": string;
  "at"?: number;
  "on"?: string;
  "match"?: Record<string, string>;
  "action": string;
  "fired": boolean;
  "fired_at"?: number;
  "created_at": number;
}

export interface TimerListRes {
  "timers": Array<Timer>;
}

export interface TranscriptChunk {
  "seq": number;
  "stream": number;
  "at": number;
  "data": Uint8Array;
}

export interface TranscriptGap {
  "from": number;
  "to": number;
}

export interface TranscriptRecord {
  "index": number;
  "run": string;
  "seq": number;
  "stream": number;
  "at": number;
  "data": Uint8Array;
}

export interface Usage {
  "budget_id": string;
  "window": string;
  "since": number;
  "requests": number;
  "tokens": number;
  "estimated_cost_micros": number;
  "active_reservations": number;
  "unmetered_requests": number;
  "incomplete_requests": number;
}

export interface UsageReq {
  "tenant"?: string;
  "ws"?: string;
  "principal"?: string;
  "binding"?: string;
  "window"?: string;
}

export interface UsageRes {
  "usage": Array<Usage>;
}

export interface Volume {
  "id": string;
  "tenant": string;
  "owner": string;
  "artifact": string;
  "version": number;
  "versions": Array<VolumeVersion>;
  "created_at": number;
  "updated_at": number;
}

export interface VolumeArchiveReq {
  "ws": string;
  "path": string;
  "upload": boolean;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface VolumeAttachReq {
  "id": string;
  "ws": string;
  "generation": number;
  "path": string;
  "idem"?: string;
}

export interface VolumeCreateReq {
  "id": string;
  "artifact": string;
  "idem"?: string;
}

export interface VolumeDetachReq {
  "ws": string;
  "generation": number;
  "path": string;
  "idem"?: string;
}

export interface VolumeGetReq {
  "id": string;
}

export interface VolumeListRes {
  "volumes": Array<Volume>;
}

export interface VolumeMount {
  "id": string;
  "path": string;
  "version"?: number;
  "artifact"?: string;
}

export interface VolumePublishPathReq {
  "ws": string;
  "path": string;
  "volume": string;
  "expected_version": number;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface VolumePublishReq {
  "id": string;
  "ws": string;
  "generation": number;
  "artifact": string;
  "expected_version": number;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface VolumeRemoveReq {
  "id": string;
  "idem"?: string;
}

export interface VolumeVersion {
  "number": number;
  "artifact": string;
  "published_by"?: string;
  "generation"?: number;
  "published_at": number;
}

export interface WSACLReq {
  "id": string;
  "acl": WorkspaceACL;
  "idem"?: string;
}

export interface WSClaimReq {
  "id": string;
}

export interface WSClaimRes {
  "workspace": Workspace;
  "lease_sec": number;
}

export interface WSCreateReq {
  "spec": WorkspaceSpec;
  "idem"?: string;
}

export interface WSDiag {
  "id": string;
  "gen": number;
  "backend": string;
  "root": string;
  "volumes"?: Array<VolumeMount>;
  "bytes": number;
  "files": number;
  "broker"?: string;
  "bindings"?: Array<string>;
  "lease_ends"?: number;
  "sessions"?: Array<SessionStatus>;
}

export interface WSGetReq {
  "id": string;
  "idem"?: string;
  "grant"?: Grant | null;
}

export interface WSInfoRes {
  "ws": string;
  "backend": string;
  "root"?: string;
  "sessions"?: Array<string>;
  "broker"?: string;
}

export interface WSListRes {
  "workspaces": Array<Workspace>;
}

export interface WSMoveReq {
  "id": string;
  "requires"?: Requires | null;
  "placement"?: Placement | null;
  "idem"?: string;
}

export interface WSQuarantineCommitReq {
  "operation": string;
  "ws": string;
  "gen": number;
  "backend": string;
  "snapshot": string;
  "snapshot_format"?: string;
}

export interface WSQuarantineReq {
  "operation": string;
  "ws": string;
  "gen": number;
  "action": string;
  "backend"?: string;
  "exclude"?: Array<string>;
  "security"?: SecuritySpec;
  "tenant"?: string;
  "volumes"?: Array<VolumeMount>;
}

export interface WSQuarantineRes {
  "fenced": boolean;
  "gen": number;
  "action": string;
  "backend"?: string;
  "snapshot"?: string;
  "snapshot_format"?: string;
  "warning"?: string;
}

export interface WSReadyReq {
  "id": string;
  "gen": number;
  "restore_processes"?: string;
}

export interface WSReleaseCommitReq {
  "id": string;
  "gen": number;
  "operation"?: string;
  "snapshot"?: string;
  "snapshot_format"?: string;
}

export interface WSReleaseReq {
  "ws": string;
  "gen": number;
  "release_epoch"?: number;
  "operation"?: string;
  "snapshot": boolean;
  "reason"?: string;
  "tenant"?: string;
  "backend"?: string;
  "spec"?: WorkspaceSpec;
}

export interface WSReleasedReq {
  "id": string;
  "gen": number;
  "operation"?: string;
  "snapshot"?: string;
  "snapshot_format"?: string;
  "reason"?: string;
  "failed"?: boolean;
  "preparing"?: boolean;
}

export interface WSRenewReq {
  "ids": Array<string>;
  "gen"?: Record<string, number>;
  "controller_epoch"?: number;
  "authz"?: Record<string, number>;
}

export interface WSRenewRes {
  "results": Array<WSRenewResult>;
  "controller_epoch"?: number;
}

export interface WSRenewResult {
  "id": string;
  "gen": number;
  "accepted": boolean;
  "authoritative_gen"?: number;
  "lease_until"?: number;
  "action": string;
  "controller_epoch"?: number;
  "authz_revision"?: number;
  "revoked"?: Array<string>;
  "authz_reset"?: boolean;
}

export interface WSSleepReq {
  "id": string;
  "after_sec"?: number;
  "at"?: number;
  "on"?: string;
  "match"?: Record<string, string>;
  "idem"?: string;
}

export interface WSSnapshotCommitReq {
  "id": string;
  "gen": number;
  "snapshot": string;
  "format"?: string;
}

export interface WSSnapshotReq {
  "ws": string;
  "upload": boolean;
  "authoritative"?: boolean;
  "idem"?: string;
  "grant"?: Grant | null;
  "gen"?: number;
}

export interface WSSnapshotRes {
  "artifact": string;
  "bytes": number;
  "consistency": string;
  "authoritative": boolean;
  "format"?: string;
  "uploaded_bytes"?: number;
  "chunks"?: number;
  "uploaded_chunks"?: number;
}

export interface Workspace {
  "id": string;
  "spec": WorkspaceSpec;
  "state": string;
  "node"?: string;
  "lease_until"?: number;
  "last_snapshot"?: string;
  "last_snapshot_format"?: string;
  "last_snapshot_objects"?: Array<string>;
  "created_at": number;
  "updated_at": number;
  "gen": number;
  "tenant"?: string;
  "owner"?: string;
  "authz_revision"?: number;
  "revocations"?: Array<AuthzRevocation>;
  "revocation_floor"?: number;
  "release_epoch"?: number;
  "release_operation"?: string;
  "quarantine_operation"?: string;
  "quarantined_at"?: number;
}

export interface WorkspaceACL {
  "readers"?: Array<string>;
  "writers"?: Array<string>;
}

export interface WorkspaceSelector {
  "all"?: boolean;
  "workspace"?: string;
  "tenant"?: string;
  "principal"?: string;
  "run"?: string;
  "node"?: string;
  "model"?: string;
  "backend"?: string;
  "labels"?: Record<string, string>;
  "created_after"?: number;
  "created_before"?: number;
}

export interface WorkspaceSpec {
  "name"?: string;
  "run"?: string;
  "model"?: string;
  "labels"?: Record<string, string>;
  "image"?: string;
  "restore_from"?: string;
  "restore_format"?: string;
  "restore_objects"?: Array<string>;
  "base"?: string;
  "requires": Requires;
  "placement": Placement;
  "bindings"?: Array<string>;
  "env"?: Record<string, string>;
  "principal"?: string;
  "idle": Idle;
  "exclude"?: Array<string>;
  "security"?: SecuritySpec;
  "acl"?: WorkspaceACL;
  "mount_path"?: string;
  "repo"?: RepoSpec;
  "volumes"?: Array<VolumeMount>;
}

export const OPERATIONS = {
  "agent.approval.decided": { constant: "OpAgentApprovalDecided", request: "AgentApprovalDecidedReq", response: "" },
  "agent.cancel": { constant: "OpAgentCancel", request: "AgentGetReq", response: "Agent" },
  "agent.create": { constant: "OpAgentCreate", request: "AgentCreateReq", response: "Agent" },
  "agent.deliver": { constant: "OpAgentDeliver", request: "AgentDeliverReq", response: "" },
  "agent.destroy": { constant: "OpAgentDestroy", request: "AgentGetReq", response: "" },
  "agent.fork": { constant: "OpAgentFork", request: "AgentForkReq", response: "Agent" },
  "agent.get": { constant: "OpAgentGet", request: "AgentGetReq", response: "Agent" },
  "agent.list": { constant: "OpAgentList", request: "AgentListReq", response: "AgentListRes" },
  "agent.message": { constant: "OpAgentMessage", request: "AgentMessageReq", response: "AgentMessageRes" },
  "agent.report": { constant: "OpAgentReport", request: "AgentReport", response: "" },
  "agent.run": { constant: "OpAgentRun", request: "AgentRunReq", response: "AgentRunRes" },
  "agent.run.cancel": { constant: "OpAgentRunCancel", request: "AgentRunCancelReq", response: "" },
  "agent.sleep": { constant: "OpAgentSleep", request: "AgentGetReq", response: "Agent" },
  "agent.transcript": { constant: "OpAgentTranscript", request: "AgentTranscriptReq", response: "AgentTranscriptRes" },
  "agent.wake": { constant: "OpAgentWake", request: "AgentWakeReq", response: "Agent" },
  "approval.decide": { constant: "OpApprovalDecide", request: "ApprovalDecideReq", response: "Approval" },
  "approval.get": { constant: "OpApprovalGet", request: "ApprovalGetReq", response: "Approval" },
  "approval.list": { constant: "OpApprovalList", request: "ApprovalListReq", response: "ApprovalListRes" },
  "artifact.proof": { constant: "OpArtifactProof", request: "ArtifactProofReq", response: "ArtifactProofRes" },
  "audit.export": { constant: "OpAuditExport", request: "AuditExportReq", response: "AuditExportRes" },
  "audit.key": { constant: "OpAuditKey", request: "AuditKeyReq", response: "AuditKeyRes" },
  "base.create": { constant: "OpBaseCreate", request: "BaseCreateReq", response: "Base" },
  "base.list": { constant: "OpBaseList", request: "", response: "BaseListRes" },
  "base.remove": { constant: "OpBaseRemove", request: "BaseRemoveReq", response: "" },
  "binding.lease": { constant: "OpBindingLease", request: "BindingLeaseReq", response: "BindingLeaseRes" },
  "budget.create": { constant: "OpBudgetCreate", request: "BudgetCreateReq", response: "Budget" },
  "budget.list": { constant: "OpBudgetList", request: "BudgetListReq", response: "BudgetListRes" },
  "budget.remove": { constant: "OpBudgetRemove", request: "BudgetRemoveReq", response: "" },
  "budget.reserve": { constant: "OpBudgetReserve", request: "BudgetReserveReq", response: "BudgetReservation" },
  "budget.settle": { constant: "OpBudgetSettle", request: "BudgetSettleReq", response: "BudgetSettlement" },
  "computer.close": { constant: "OpComputerClose", request: "ComputerCloseReq", response: "" },
  "computer.create": { constant: "OpComputerCreate", request: "ComputerCreateReq", response: "ComputerCreateRes" },
  "computer.downloads": { constant: "OpComputerDownloads", request: "ComputerDownloadsReq", response: "ComputerDownloadsRes" },
  "computer.eval": { constant: "OpComputerEval", request: "ComputerEvalReq", response: "ComputerEvalRes" },
  "computer.get": { constant: "OpComputerGet", request: "ComputerGetReq", response: "ComputerGetRes" },
  "computer.input": { constant: "OpComputerInput", request: "ComputerInputReq", response: "ComputerInputRes" },
  "computer.navigate": { constant: "OpComputerNavigate", request: "ComputerNavigateReq", response: "ComputerNavigateRes" },
  "computer.screenshot": { constant: "OpComputerScreenshot", request: "ComputerScreenshotReq", response: "ComputerScreenshotRes" },
  "controller.state": { constant: "OpControllerState", request: "", response: "" },
  "diag": { constant: "OpDiag", request: "DiagReq", response: "ControlDiag" },
  "e2ee.kx": { constant: "OpE2EEKeyExchange", request: "", response: "" },
  "e2ee.sealed": { constant: "OpE2EESealed", request: "", response: "" },
  "egress.approval": { constant: "OpEgressApproval", request: "EgressApprovalReq", response: "EgressApprovalRes" },
  "events.post": { constant: "OpEventsPost", request: "EventPost", response: "" },
  "events.stop": { constant: "OpEventsStop", request: "EventsStopReq", response: "" },
  "events.tail": { constant: "OpEventsTail", request: "EventsTailReq", response: "" },
  "fleet.get": { constant: "OpFleetGet", request: "FleetGetReq", response: "FleetOperation" },
  "fleet.list": { constant: "OpFleetList", request: "", response: "FleetListRes" },
  "fleet.quarantine": { constant: "OpFleetQuarantine", request: "FleetQuarantineReq", response: "FleetOperation" },
  "fs.apply_tar": { constant: "OpFSApplyTar", request: "FSApplyTarReq", response: "FSApplyTarRes" },
  "fs.edit": { constant: "OpFSEdit", request: "FSEditReq", response: "FSEditRes" },
  "fs.list": { constant: "OpFSList", request: "FSListReq", response: "FSListRes" },
  "fs.mkdir": { constant: "OpFSMkdir", request: "FSMkdirReq", response: "" },
  "fs.read": { constant: "OpFSRead", request: "FSReadReq", response: "FSReadRes" },
  "fs.remove": { constant: "OpFSRemove", request: "FSRemoveReq", response: "" },
  "fs.rename": { constant: "OpFSRename", request: "FSRenameReq", response: "" },
  "fs.search": { constant: "OpFSSearch", request: "FSSearchReq", response: "FSSearchRes" },
  "fs.stat": { constant: "OpFSStat", request: "", response: "FSStatRes" },
  "fs.write": { constant: "OpFSWrite", request: "FSWriteReq", response: "" },
  "grant": { constant: "OpGrant", request: "GrantReq", response: "Grant" },
  "node.diag": { constant: "OpNodeDiag", request: "NodeDiagReq", response: "NodeDiag" },
  "node.list": { constant: "OpNodeList", request: "", response: "NodeListRes" },
  "node.status": { constant: "OpNodeStatus", request: "", response: "NodeStatus" },
  "pool.create": { constant: "OpPoolCreate", request: "PoolCreateReq", response: "Pool" },
  "pool.get": { constant: "OpPoolGet", request: "PoolGetReq", response: "Pool" },
  "pool.list": { constant: "OpPoolList", request: "", response: "PoolListRes" },
  "pool.remove": { constant: "OpPoolRemove", request: "PoolRemoveReq", response: "" },
  "port.open": { constant: "OpPortOpen", request: "PortOpenReq", response: "SOpenRes" },
  "principal.create": { constant: "OpPrincipalCreate", request: "PrincipalCreateReq", response: "" },
  "principal.invite": { constant: "OpPrincipalInvite", request: "PrincipalInviteReq", response: "" },
  "principal.list": { constant: "OpPrincipalList", request: "PrincipalListReq", response: "PrincipalListRes" },
  "principal.revoke": { constant: "OpPrincipalRevoke", request: "PrincipalRevokeReq", response: "PrincipalRevokeRes" },
  "principal.token.issue": { constant: "OpPrincipalTokenIssue", request: "PrincipalTokenIssueReq", response: "PrincipalTokenIssueRes" },
  "queue.advance": { constant: "OpQueueAdvance", request: "QueueAdvanceReq", response: "Queue" },
  "queue.create": { constant: "OpQueueCreate", request: "QueueCreateReq", response: "Queue" },
  "queue.get": { constant: "OpQueueGet", request: "QueueGetReq", response: "Queue" },
  "queue.list": { constant: "OpQueueList", request: "QueueListReq", response: "QueueListRes" },
  "s.ack": { constant: "OpSAck", request: "SAckReq", response: "" },
  "s.attach": { constant: "OpSAttach", request: "SAttachReq", response: "SOpenRes" },
  "s.close": { constant: "OpSClose", request: "SCloseReq", response: "" },
  "s.input": { constant: "OpSInput", request: "SInputReq", response: "" },
  "s.list": { constant: "OpSList", request: "SListReq", response: "SListRes" },
  "s.open": { constant: "OpSOpen", request: "SOpenReq", response: "SOpenRes" },
  "s.resize": { constant: "OpSResize", request: "SResizeReq", response: "" },
  "s.signal": { constant: "OpSSignal", request: "SSignalReq", response: "" },
  "s.wait": { constant: "OpSWait", request: "SWaitReq", response: "SWaitRes" },
  "session.cap.check": { constant: "OpSessionCapabilityCheck", request: "SessionCapabilityCheckReq", response: "SessionCapabilityCheckRes" },
  "session.cap.issue": { constant: "OpSessionCapabilityIssue", request: "SessionCapabilityIssueReq", response: "SessionCapabilityIssueRes" },
  "session.cap.renew": { constant: "OpSessionCapabilityRenew", request: "SessionCapabilityRenewReq", response: "" },
  "session.log.commit": { constant: "OpSessionLogCommit", request: "SessionLogCommitReq", response: "" },
  "session.log.delete": { constant: "OpSessionLogDelete", request: "", response: "" },
  "session.log.get": { constant: "OpSessionLogGet", request: "SessionLogGetReq", response: "" },
  "tenant.create": { constant: "OpTenantCreate", request: "TenantCreateReq", response: "" },
  "tenant.get": { constant: "OpTenantGet", request: "TenantGetReq", response: "" },
  "tenant.list": { constant: "OpTenantList", request: "", response: "TenantListRes" },
  "tenant.state": { constant: "OpTenantState", request: "TenantStateReq", response: "" },
  "tenant.update": { constant: "OpTenantUpdate", request: "TenantUpdateReq", response: "" },
  "tenant.usage": { constant: "OpTenantUsage", request: "TenantUsageReq", response: "" },
  "timer.list": { constant: "OpTimerList", request: "", response: "TimerListRes" },
  "usage.get": { constant: "OpUsageGet", request: "UsageReq", response: "UsageRes" },
  "volume.archive": { constant: "OpVolumeArchive", request: "VolumeArchiveReq", response: "WSSnapshotRes" },
  "volume.attach": { constant: "OpVolumeAttach", request: "VolumeAttachReq", response: "Workspace" },
  "volume.create": { constant: "OpVolumeCreate", request: "VolumeCreateReq", response: "Volume" },
  "volume.detach": { constant: "OpVolumeDetach", request: "VolumeDetachReq", response: "Workspace" },
  "volume.get": { constant: "OpVolumeGet", request: "VolumeGetReq", response: "Volume" },
  "volume.list": { constant: "OpVolumeList", request: "", response: "VolumeListRes" },
  "volume.publish": { constant: "OpVolumePublish", request: "VolumePublishReq", response: "" },
  "volume.publish.commit": { constant: "OpVolumePublishCommit", request: "", response: "" },
  "volume.remove": { constant: "OpVolumeRemove", request: "VolumeRemoveReq", response: "" },
  "ws.acl": { constant: "OpWSACL", request: "WSACLReq", response: "Workspace" },
  "ws.claim": { constant: "OpWSClaim", request: "WSClaimReq", response: "WSClaimRes" },
  "ws.create": { constant: "OpWSCreate", request: "WSCreateReq", response: "Workspace" },
  "ws.destroy": { constant: "OpWSDestroy", request: "WSGetReq", response: "" },
  "ws.get": { constant: "OpWSGet", request: "WSGetReq", response: "Workspace" },
  "ws.info": { constant: "OpWSInfo", request: "WSGetReq", response: "WSInfoRes" },
  "ws.list": { constant: "OpWSList", request: "", response: "WSListRes" },
  "ws.move": { constant: "OpWSMove", request: "WSMoveReq", response: "Workspace" },
  "ws.quarantine": { constant: "OpWSQuarantine", request: "WSQuarantineReq", response: "WSQuarantineRes" },
  "ws.quarantine.commit": { constant: "OpWSQuarantineCommit", request: "WSQuarantineCommitReq", response: "" },
  "ws.ready": { constant: "OpWSReady", request: "WSReadyReq", response: "" },
  "ws.release": { constant: "OpWSRelease", request: "WSReleaseReq", response: "" },
  "ws.release.abort": { constant: "OpWSReleaseAbort", request: "", response: "" },
  "ws.release.abort.commit": { constant: "OpWSReleaseAbortCommit", request: "", response: "" },
  "ws.release.commit": { constant: "OpWSReleaseCommit", request: "WSReleaseCommitReq", response: "" },
  "ws.released": { constant: "OpWSReleased", request: "WSReleasedReq", response: "" },
  "ws.renew": { constant: "OpWSRenew", request: "WSRenewReq", response: "WSRenewRes" },
  "ws.sleep": { constant: "OpWSSleep", request: "WSSleepReq", response: "Timer" },
  "ws.snapshot": { constant: "OpWSSnapshot", request: "WSSnapshotReq", response: "WSSnapshotRes" },
  "ws.snapshot.commit": { constant: "OpWSSnapshotCommit", request: "WSSnapshotCommitReq", response: "" },
  "ws.wake": { constant: "OpWSWake", request: "WSGetReq", response: "Workspace" },
} as const;
