# Code generated by cmd/protogen; DO NOT EDIT.
from __future__ import annotations

from typing import Any, NotRequired, Optional, Required, TypedDict

ACPCapabilities = TypedDict("ACPCapabilities", {
    "load_session": NotRequired[bool],
    "resume_session": NotRequired[bool],
    "close_session": NotRequired[bool],
    "additional_directories": NotRequired[bool],
}, total=False)

ACPFrameRecord = TypedDict("ACPFrameRecord", {
    "at": Required[int],
    "frame": Required[Any],
    "replayed": NotRequired[bool],
    "redacted": NotRequired[bool],
    "truncated": NotRequired[bool],
}, total=False)

ACPRecordAssembler = TypedDict("ACPRecordAssembler", {
}, total=False)

Agent = TypedDict("Agent", {
    "id": Required[str],
    "tenant": Required[str],
    "owner": Required[str],
    "name": NotRequired[str],
    "ws": Required[str],
    "owns_ws": NotRequired[bool],
    "spec": Required["AgentSpec"],
    "mode": Required[str],
    "acp_session_id": NotRequired[str],
    "capabilities": NotRequired[Optional["ACPCapabilities"]],
    "status": Required[str],
    "status_reason": NotRequired[str],
    "inbox": Required[list["AgentMessage"]],
    "runs": Required[list["AgentRun"]],
    "turns": Required[int],
    "parent": NotRequired[str],
    "forked_from": NotRequired[str],
    "policy": Required["AgentPolicy"],
    "transcript_session": NotRequired[str],
    "transcript_node": NotRequired[str],
    "transcript_next": NotRequired[int],
    "transcript_first": NotRequired[int],
    "transcript_bytes": NotRequired[int],
    "pending_approvals": NotRequired[int],
    "url": NotRequired[str],
    "created_at": Required[int],
    "updated_at": Required[int],
    "wake_timer": NotRequired[str],
    "idle_since": NotRequired[int],
    "failures": NotRequired[int],
    "parent_notified": NotRequired[bool],
}, total=False)

AgentApprovalDecidedReq = TypedDict("AgentApprovalDecidedReq", {
    "agent": Required[str],
    "run": Required[str],
    "approval": Required[str],
    "decision": Required["ApprovalDecision"],
}, total=False)

AgentCreateReq = TypedDict("AgentCreateReq", {
    "name": NotRequired[str],
    "ws": NotRequired[str],
    "workspace": NotRequired[Optional["WorkspaceSpec"]],
    "spec": Required["AgentSpec"],
    "policy": Required["AgentPolicy"],
    "parent": NotRequired[str],
    "acp_session_id": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

AgentDeliverReq = TypedDict("AgentDeliverReq", {
    "agent": Required[str],
    "run": Required[str],
    "message": Required["AgentMessage"],
}, total=False)

AgentForkReq = TypedDict("AgentForkReq", {
    "id": Required[str],
    "name": NotRequired[str],
    "task": NotRequired[str],
    "policy": NotRequired[Optional["AgentPolicy"]],
    "idem": NotRequired[str],
}, total=False)

AgentGetReq = TypedDict("AgentGetReq", {
    "id": Required[str],
    "idem": NotRequired[str],
}, total=False)

AgentListReq = TypedDict("AgentListReq", {
    "status": NotRequired[str],
    "ws": NotRequired[str],
    "parent": NotRequired[str],
}, total=False)

AgentListRes = TypedDict("AgentListRes", {
    "agents": Required[list["Agent"]],
}, total=False)

AgentMessage = TypedDict("AgentMessage", {
    "id": Required[str],
    "kind": Required[str],
    "text": Required[str],
    "by": NotRequired[str],
    "at": Required[int],
}, total=False)

AgentMessageReq = TypedDict("AgentMessageReq", {
    "id": Required[str],
    "text": Required[str],
    "kind": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

AgentMessageRes = TypedDict("AgentMessageRes", {
    "agent": Required["Agent"],
    "message": Required["AgentMessage"],
    "degraded": NotRequired[bool],
    "woken": NotRequired[bool],
}, total=False)

AgentPolicy = TypedDict("AgentPolicy", {
    "sleep_after_sec": NotRequired[int],
    "approve": NotRequired[str],
    "max_turns": NotRequired[int],
    "start_at": NotRequired[int],
}, total=False)

AgentReport = TypedDict("AgentReport", {
    "agent": Required[str],
    "run": Required[str],
    "ws": Required[str],
    "gen": Required[int],
    "seq": Required[int],
    "kind": Required[str],
    "at": Required[int],
    "transcript": NotRequired[str],
    "acp_session_id": NotRequired[str],
    "capabilities": NotRequired[Optional["ACPCapabilities"]],
    "loaded": NotRequired[bool],
    "message": NotRequired[str],
    "stop_reason": NotRequired[str],
    "error": NotRequired[str],
    "exit_code": NotRequired[int],
    "cancelled": NotRequired[bool],
    "tool_call": NotRequired[str],
    "tool_kind": NotRequired[str],
    "tool_title": NotRequired[str],
    "tool_status": NotRequired[str],
    "locations": NotRequired[list[str]],
    "approval": NotRequired[Optional["Approval"]],
    "usage": NotRequired[Optional["AgentUsage"]],
    "chunks": NotRequired[list["TranscriptChunk"]],
}, total=False)

AgentRun = TypedDict("AgentRun", {
    "id": Required[str],
    "attempt": Required[int],
    "node": NotRequired[str],
    "gen": NotRequired[int],
    "state": Required[str],
    "transcript": NotRequired[str],
    "loaded": NotRequired[bool],
    "started_at": NotRequired[int],
    "finished_at": NotRequired[int],
    "stop_reason": NotRequired[str],
    "error": NotRequired[str],
    "turns": Required[int],
    "last_report": NotRequired[int],
    "turn_message": NotRequired[str],
}, total=False)

AgentRunCancelReq = TypedDict("AgentRunCancelReq", {
    "agent": Required[str],
    "run": Required[str],
    "reason": NotRequired[str],
}, total=False)

AgentRunReq = TypedDict("AgentRunReq", {
    "agent": Required[str],
    "run": Required[str],
    "attempt": Required[int],
    "ws": Required[str],
    "gen": Required[int],
    "tenant": Required[str],
    "owner": Required[str],
    "spec": Required["AgentSpec"],
    "policy": Required["AgentPolicy"],
    "mode": Required[str],
    "acp_session_id": NotRequired[str],
    "messages": Required[list["AgentMessage"]],
}, total=False)

AgentRunRes = TypedDict("AgentRunRes", {
    "transcript": Required[str],
}, total=False)

AgentSpec = TypedDict("AgentSpec", {
    "recipe": Required[str],
    "recipe_yaml": NotRequired[str],
    "task": Required[str],
    "providers": NotRequired[list[str]],
    "primary": NotRequired[str],
    "binding_specs": NotRequired[list[str]],
    "model": NotRequired[str],
    "sandbox": NotRequired[str],
    "acp_command": NotRequired[list[str]],
    "auth": NotRequired[str],
    "mode": NotRequired[str],
}, total=False)

AgentTranscriptReq = TypedDict("AgentTranscriptReq", {
    "id": Required[str],
    "from": NotRequired[int],
    "limit": NotRequired[int],
}, total=False)

AgentTranscriptRes = TypedDict("AgentTranscriptRes", {
    "records": Required[list["TranscriptRecord"]],
    "next": Required[int],
    "gap": NotRequired[Optional["TranscriptGap"]],
    "done": NotRequired[bool],
}, total=False)

AgentUsage = TypedDict("AgentUsage", {
    "input": NotRequired[int],
    "output": NotRequired[int],
}, total=False)

AgentWakeReq = TypedDict("AgentWakeReq", {
    "id": Required[str],
    "by": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

Approval = TypedDict("Approval", {
    "id": Required[str],
    "tenant": Required[str],
    "owner": Required[str],
    "agent": NotRequired[str],
    "ws": NotRequired[str],
    "run": NotRequired[str],
    "principal": NotRequired[str],
    "rule": NotRequired[str],
    "host": NotRequired[str],
    "method": NotRequired[str],
    "path_hash": NotRequired[str],
    "body_hash": NotRequired[str],
    "fingerprint": NotRequired[str],
    "kind": Required[str],
    "title": NotRequired[str],
    "tool_call": NotRequired[str],
    "tool_kind": NotRequired[str],
    "locations": NotRequired[list[str]],
    "options": NotRequired[list["ApprovalOption"]],
    "detail": NotRequired[Any],
    "status": Required[str],
    "decision": NotRequired[Optional["ApprovalDecision"]],
    "delivered_at": NotRequired[int],
    "created_at": Required[int],
    "updated_at": Required[int],
    "expires_at": NotRequired[int],
}, total=False)

ApprovalDecideReq = TypedDict("ApprovalDecideReq", {
    "id": Required[str],
    "option": NotRequired[str],
    "denied": NotRequired[bool],
    "content": NotRequired[Any],
    "remember": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

ApprovalDecision = TypedDict("ApprovalDecision", {
    "option": NotRequired[str],
    "denied": NotRequired[bool],
    "content": NotRequired[Any],
    "by": Required[str],
    "at": Required[int],
    "remember": NotRequired[str],
}, total=False)

ApprovalGetReq = TypedDict("ApprovalGetReq", {
    "id": Required[str],
}, total=False)

ApprovalListReq = TypedDict("ApprovalListReq", {
    "agent": NotRequired[str],
    "kind": NotRequired[str],
    "status": NotRequired[str],
}, total=False)

ApprovalListRes = TypedDict("ApprovalListRes", {
    "approvals": Required[list["Approval"]],
}, total=False)

ApprovalOption = TypedDict("ApprovalOption", {
    "id": Required[str],
    "name": NotRequired[str],
    "kind": NotRequired[str],
}, total=False)

ArtifactProofClaims = TypedDict("ArtifactProofClaims", {
    "id": Required[str],
    "node": Required[str],
    "tenant": Required[str],
    "ws": Required[str],
    "gen": Required[int],
    "method": Required[str],
    "artifact": Required[str],
    "issued_at": Required[int],
    "expires_at": Required[int],
}, total=False)

ArtifactProofEnvelope = TypedDict("ArtifactProofEnvelope", {
    "claims": Required["ArtifactProofClaims"],
    "signature": Required[bytes],
}, total=False)

ArtifactProofReq = TypedDict("ArtifactProofReq", {
    "ws": Required[str],
    "gen": Required[int],
    "method": Required[str],
    "artifact": Required[str],
}, total=False)

ArtifactProofRes = TypedDict("ArtifactProofRes", {
    "proof": Required[str],
}, total=False)

AuditExportReq = TypedDict("AuditExportReq", {
    "tenant": NotRequired[str],
    "from": Required[int],
    "to": Required[int],
}, total=False)

AuditExportRes = TypedDict("AuditExportRes", {
    "manifest": Required["AuditManifest"],
    "signature": Required[str],
    "bundle": Required[bytes],
}, total=False)

AuditKeyReq = TypedDict("AuditKeyReq", {
}, total=False)

AuditKeyRes = TypedDict("AuditKeyRes", {
    "key_id": Required[str],
    "algorithm": Required[str],
    "public_key": Required[str],
}, total=False)

AuditManifest = TypedDict("AuditManifest", {
    "schema": Required[str],
    "tenant": Required[str],
    "range_from": Required[int],
    "range_to": Required[int],
    "created_at": Required[int],
    "event_count": Required[int],
    "first_seq": NotRequired[int],
    "last_seq": NotRequired[int],
    "payload_bytes": Required[int],
    "payload_sha256": Required[str],
    "hash_algorithm": Required[str],
    "signature_algorithm": Required[str],
    "key_id": Required[str],
}, total=False)

AuditPolicy = TypedDict("AuditPolicy", {
    "required": NotRequired[bool],
}, total=False)

AuthzRevocation = TypedDict("AuthzRevocation", {
    "rev": Required[int],
    "principal": Required[str],
}, total=False)

BackendDescriptor = TypedDict("BackendDescriptor", {
    "name": Required[str],
    "security": Required["BackendSecurityCaps"],
    "runtime": Required["RuntimeCaps"],
}, total=False)

BackendSecurityCaps = TypedDict("BackendSecurityCaps", {
    "isolation": Required[str],
    "multi_tenant": Required[bool],
    "sibling_isolation": Required[bool],
    "egress_mode": Required[str],
    "broker_identity": Required[str],
    "filesystem_boundary": Required[str],
    "network_namespace": Required[bool],
    "device_isolation": Required[bool],
}, total=False)

Base = TypedDict("Base", {
    "name": Required[str],
    "tenant": Required[str],
    "owner": Required[str],
    "artifact": Required[str],
    "format": NotRequired[str],
    "objects": NotRequired[list[str]],
    "workspace": NotRequired[str],
    "bytes": NotRequired[int],
    "created_at": Required[int],
}, total=False)

BaseCreateReq = TypedDict("BaseCreateReq", {
    "name": Required[str],
    "artifact": Required[str],
    "format": NotRequired[str],
    "workspace": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

BaseListRes = TypedDict("BaseListRes", {
    "bases": Required[list["Base"]],
}, total=False)

BaseRemoveReq = TypedDict("BaseRemoveReq", {
    "name": Required[str],
    "idem": NotRequired[str],
}, total=False)

BindingLease = TypedDict("BindingLease", {
    "id": Required[str],
    "secret": Required[str],
    "destinations": Required[list[str]],
    "shape": NotRequired[str],
    "principals": NotRequired[list[str]],
    "expires_at": Required[int],
    "placeholder": NotRequired[str],
}, total=False)

BindingLeaseReq = TypedDict("BindingLeaseReq", {
    "ws": Required[str],
    "gen": NotRequired[int],
}, total=False)

BindingLeaseRes = TypedDict("BindingLeaseRes", {
    "leases": Required[list["BindingLease"]],
}, total=False)

Budget = TypedDict("Budget", {
    "id": Required[str],
    "tenant": NotRequired[str],
    "attach_to": Required[str],
    "attach_id": Required[str],
    "window": Required[str],
    "max_requests": NotRequired[int],
    "max_tokens": NotRequired[int],
    "max_estimated_cost_micros": NotRequired[int],
    "created_at": NotRequired[int],
    "updated_at": NotRequired[int],
}, total=False)

BudgetCreateReq = TypedDict("BudgetCreateReq", {
    "budget": Required["Budget"],
    "idem": NotRequired[str],
}, total=False)

BudgetListReq = TypedDict("BudgetListReq", {
}, total=False)

BudgetListRes = TypedDict("BudgetListRes", {
    "budgets": Required[list["Budget"]],
}, total=False)

BudgetRemoveReq = TypedDict("BudgetRemoveReq", {
    "id": Required[str],
    "idem": NotRequired[str],
}, total=False)

BudgetReservation = TypedDict("BudgetReservation", {
    "id": NotRequired[str],
    "tracked": NotRequired[bool],
    "budget_ids": NotRequired[list[str]],
    "unmetered_reason": NotRequired[str],
    "expires_at": NotRequired[int],
    "denied": NotRequired[bool],
    "limit": NotRequired[str],
}, total=False)

BudgetReserveReq = TypedDict("BudgetReserveReq", {
    "key": Required[str],
    "ws": Required[str],
    "gen": Required[int],
    "principal": NotRequired[str],
    "bindings": NotRequired[list[str]],
    "provider": Required[str],
    "model": NotRequired[str],
    "input_tokens": NotRequired[int],
    "max_output_tokens": NotRequired[int],
    "metered": NotRequired[bool],
}, total=False)

BudgetSettleReq = TypedDict("BudgetSettleReq", {
    "reservation": Required[str],
    "mode": Required[str],
    "input_tokens": NotRequired[int],
    "output_tokens": NotRequired[int],
}, total=False)

BudgetSettlement = TypedDict("BudgetSettlement", {
    "reservation": Required[str],
    "mode": Required[str],
    "tokens": NotRequired[int],
    "estimated_cost_micros": NotRequired[int],
    "estimated_cost_unavailable": NotRequired[bool],
    "usage_exceeded_reservation": NotRequired[bool],
}, total=False)

ChildSummary = TypedDict("ChildSummary", {
    "child": Required[str],
    "name": NotRequired[str],
    "status": Required[str],
    "reason": NotRequired[str],
    "turns": Required[int],
    "ws": Required[str],
    "url": NotRequired[str],
}, total=False)

ChunkBody = TypedDict("ChunkBody", {
    "st": Required[int],
    "d": NotRequired[bytes],
}, total=False)

ControlDiag = TypedDict("ControlDiag", {
    "now": Required[int],
    "uptime_sec": Required[int],
    "version": NotRequired[str],
    "ws_state": Required[dict[str, int]],
    "nodes_total": Required[int],
    "nodes_online": Required[int],
    "timers_pending": Required[int],
    "timers_fired": Required[int],
    "timers_max": NotRequired[int],
    "mutation_records": NotRequired[int],
    "mutation_records_max": NotRequired[int],
    "event_seq": Required[int],
    "event_oldest": NotRequired[int],
    "events_max": NotRequired[int],
    "requests_active_max": NotRequired[int],
    "bindings": NotRequired[list[str]],
    "artifact_count": Required[int],
    "artifact_bytes": Required[int],
    "artifact_reserved_bytes": NotRequired[int],
    "artifact_reserved_objects": NotRequired[int],
    "artifact_max_bytes": NotRequired[int],
    "artifact_max_objects": NotRequired[int],
    "workspaces_per_tenant_max": NotRequired[int],
    "workspaces_per_subject_max": NotRequired[int],
    "db_integrity": NotRequired[str],
    "lease_sec": Required[int],
    "controller_role": NotRequired[str],
    "controller_epoch": NotRequired[int],
    "controller_lease_age_ms": NotRequired[int],
    "last_replicated_at": NotRequired[int],
    "restored_event_seq": NotRequired[int],
    "recovery_lost_window_ms": NotRequired[int],
    "controller_reconciling": NotRequired[bool],
    "metrics": NotRequired[dict[str, float]],
    "findings": NotRequired[list["Finding"]],
}, total=False)

ControllerNodeState = TypedDict("ControllerNodeState", {
    "node": Required[str],
    "epoch": Required[int],
    "workspaces": NotRequired[list["ControllerWorkspace"]],
    "releases": NotRequired[list["ControllerReleaseState"]],
}, total=False)

ControllerReleaseState = TypedDict("ControllerReleaseState", {
    "request": Required["WSReleaseReq"],
    "response": Required["WSReleasedReq"],
    "operation_id": NotRequired[str],
    "state": Required[str],
}, total=False)

ControllerWorkspace = TypedDict("ControllerWorkspace", {
    "workspace": Required["Workspace"],
    "sessions": NotRequired[list[str]],
}, total=False)

DiagReq = TypedDict("DiagReq", {
    "verify": NotRequired[bool],
}, total=False)

E2EEKeyExchange = TypedDict("E2EEKeyExchange", {
    "type": Required[str],
    "suite": NotRequired[str],
    "caps": NotRequired[list[str]],
    "session": Required[bytes],
    "from": Required[str],
    "to": Required[str],
    "eph": NotRequired[bytes],
    "nonce": NotRequired[bytes],
    "ts": NotRequired[int],
    "binding": NotRequired["PeerBinding"],
    "sig": NotRequired[bytes],
    "reason": NotRequired[str],
}, total=False)

E2EEPayload = TypedDict("E2EEPayload", {
    "op": NotRequired[str],
    "s": NotRequired[str],
    "ws": NotRequired[str],
    "seq": NotRequired[int],
    "body": NotRequired[bytes],
    "err": NotRequired[Optional["Error"]],
}, total=False)

E2EESealed = TypedDict("E2EESealed", {
    "sid": Required[bytes],
    "n": Required[int],
    "ct": Required[bytes],
}, total=False)

EgressApprovalReq = TypedDict("EgressApprovalReq", {
    "ws": Required[str],
    "gen": Required[int],
    "principal": Required[str],
    "rule": Required[str],
    "host": Required[str],
    "method": Required[str],
    "path_hash": Required[str],
    "body_hash": Required[str],
    "fingerprint": Required[str],
    "wait_ms": NotRequired[int],
}, total=False)

EgressApprovalRes = TypedDict("EgressApprovalRes", {
    "id": Required[str],
    "status": Required[str],
    "allowed": NotRequired[bool],
    "expires_at": NotRequired[int],
}, total=False)

EgressRule = TypedDict("EgressRule", {
    "id": Required[str],
    "mode": NotRequired[str],
    "connector": NotRequired[str],
    "protocol": Required[str],
    "hosts": NotRequired[list[str]],
    "ports": NotRequired[list[int]],
    "methods": NotRequired[list[str]],
    "path_prefixes": NotRequired[list[str]],
    "max_requests": NotRequired[int],
    "max_request_bytes": NotRequired[int],
    "max_response_bytes": NotRequired[int],
    "redact": NotRequired[list[str]],
    "shared_state": NotRequired[str],
    "repos": NotRequired[list[str]],
    "push": NotRequired[bool],
}, total=False)

Error = TypedDict("Error", {
    "code": Required[str],
    "msg": NotRequired[str],
    "oldest": NotRequired[int],
}, total=False)

Event = TypedDict("Event", {
    "seq": Required[int],
    "at": Required[int],
    "stream": NotRequired[str],
    "principal": NotRequired[str],
    "node": NotRequired[str],
    "event_id": NotRequired[str],
    "received_at": NotRequired[int],
    "observed_at": NotRequired[int],
    "origin": NotRequired[str],
    "actor": NotRequired[str],
    "tenant": NotRequired[str],
    "workspace": NotRequired[str],
    "generation": NotRequired[int],
    "controller_epoch": NotRequired[int],
    "session": NotRequired[str],
    "operation_id": NotRequired[str],
    "producer_seq": NotRequired[int],
    "type": Required[str],
    "payload": NotRequired[bytes],
    "cause": NotRequired[int],
}, total=False)

EventPost = TypedDict("EventPost", {
    "events": Required[list["Event"]],
    "sub": NotRequired[str],
}, total=False)

EventsStopReq = TypedDict("EventsStopReq", {
    "sub": NotRequired[str],
}, total=False)

EventsTailReq = TypedDict("EventsTailReq", {
    "from": Required[int],
    "follow": Required[bool],
    "ws": NotRequired[str],
    "sub": NotRequired[str],
}, total=False)

ExitInfo = TypedDict("ExitInfo", {
    "code": Required[int],
    "signal": NotRequired[str],
    "error": NotRequired[str],
    "reason": NotRequired[str],
}, total=False)

FSApplyTarReq = TypedDict("FSApplyTarReq", {
    "ws": Required[str],
    "artifact": Required[str],
    "path": NotRequired[str],
    "format": NotRequired[str],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSApplyTarRes = TypedDict("FSApplyTarRes", {
    "files": Required[int],
    "dirs": Required[int],
    "bytes": Required[int],
}, total=False)

FSEdit = TypedDict("FSEdit", {
    "old": Required[str],
    "new": Required[str],
    "all": NotRequired[bool],
}, total=False)

FSEditReq = TypedDict("FSEditReq", {
    "ws": Required[str],
    "path": Required[str],
    "edits": Required[list["FSEdit"]],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSEditRes = TypedDict("FSEditRes", {
    "replacements": Required[int],
}, total=False)

FSEntry = TypedDict("FSEntry", {
    "name": Required[str],
    "size": Required[int],
    "mode": Required[int],
    "dir": Required[bool],
    "mtime": Required[int],
    "link": NotRequired[bool],
}, total=False)

FSListReq = TypedDict("FSListReq", {
    "ws": Required[str],
    "path": Required[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSListRes = TypedDict("FSListRes", {
    "entries": Required[list["FSEntry"]],
}, total=False)

FSMatch = TypedDict("FSMatch", {
    "path": Required[str],
    "line": Required[int],
    "text": Required[str],
}, total=False)

FSMkdirReq = TypedDict("FSMkdirReq", {
    "ws": Required[str],
    "path": Required[str],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSReadReq = TypedDict("FSReadReq", {
    "ws": Required[str],
    "path": Required[str],
    "offset": NotRequired[int],
    "limit": NotRequired[int],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSReadRes = TypedDict("FSReadRes", {
    "d": Required[bytes],
    "size": Required[int],
    "eof": Required[bool],
}, total=False)

FSRemoveReq = TypedDict("FSRemoveReq", {
    "ws": Required[str],
    "path": Required[str],
    "recursive": NotRequired[bool],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSRenameReq = TypedDict("FSRenameReq", {
    "ws": Required[str],
    "from": Required[str],
    "to": Required[str],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSSearchReq = TypedDict("FSSearchReq", {
    "ws": Required[str],
    "path": Required[str],
    "pattern": Required[str],
    "glob": NotRequired[str],
    "max": NotRequired[int],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

FSSearchRes = TypedDict("FSSearchRes", {
    "matches": Required[list["FSMatch"]],
    "truncated": Required[bool],
}, total=False)

FSStatRes = TypedDict("FSStatRes", {
    "entry": Required["FSEntry"],
}, total=False)

FSWriteReq = TypedDict("FSWriteReq", {
    "ws": Required[str],
    "path": Required[str],
    "d": Required[bytes],
    "mode": NotRequired[int],
    "append": NotRequired[bool],
    "mkdirp": NotRequired[bool],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

Finding = TypedDict("Finding", {
    "severity": Required[str],
    "check": Required[str],
    "subject": NotRequired[str],
    "detail": Required[str],
    "hint": NotRequired[str],
}, total=False)

FleetGetReq = TypedDict("FleetGetReq", {
    "id": Required[str],
}, total=False)

FleetListRes = TypedDict("FleetListRes", {
    "operations": Required[list["FleetOperation"]],
}, total=False)

FleetOperation = TypedDict("FleetOperation", {
    "id": Required[str],
    "selector": Required["WorkspaceSelector"],
    "action": Required[str],
    "requested_by": Required[str],
    "tenant": Required[str],
    "state": Required[str],
    "created_at": Required[int],
    "deadline": Required[int],
    "updated_at": Required[int],
    "results": Required[list["FleetOperationResult"]],
}, total=False)

FleetOperationResult = TypedDict("FleetOperationResult", {
    "workspace": Required[str],
    "node": NotRequired[str],
    "backend": NotRequired[str],
    "generation": NotRequired[int],
    "state": Required[str],
    "fenced": NotRequired[bool],
    "acknowledged": Required[bool],
    "snapshot": NotRequired[str],
    "snapshot_format": NotRequired[str],
    "snapshot_objects": NotRequired[list[str]],
    "error": NotRequired[str],
    "updated_at": Required[int],
}, total=False)

FleetQuarantineReq = TypedDict("FleetQuarantineReq", {
    "selector": Required["WorkspaceSelector"],
    "action": Required[str],
    "deadline": NotRequired[int],
    "timeout_ms": NotRequired[int],
    "idem": NotRequired[str],
}, total=False)

Frame = TypedDict("Frame", {
    "v": Required[int],
    "t": Required[str],
    "controller_epoch": NotRequired[int],
    "id": NotRequired[int],
    "seq": NotRequired[int],
    "s": NotRequired[str],
    "ws": NotRequired[str],
    "to": NotRequired[str],
    "from": NotRequired[str],
    "op": NotRequired[str],
    "body": NotRequired[bytes],
    "err": NotRequired[Optional["Error"]],
}, total=False)

Gap = TypedDict("Gap", {
    "from": Required[int],
    "to": Required[int],
    "tier": NotRequired[str],
}, total=False)

Grant = TypedDict("Grant", {
    "claims": Required["GrantClaims"],
    "sig": Required[bytes],
    "node": Required[str],
}, total=False)

GrantClaims = TypedDict("GrantClaims", {
    "client": Required[str],
    "ws": Required[str],
    "node": Required[str],
    "principal": NotRequired[str],
    "tenant": NotRequired[str],
    "roles": NotRequired[list[str]],
    "authz_revision": NotRequired[int],
    "exp": Required[int],
    "gen": Required[int],
    "controller_epoch": NotRequired[int],
}, total=False)

GrantReq = TypedDict("GrantReq", {
    "ws": Required[str],
}, total=False)

Hello = TypedDict("Hello", {
    "peer": Required[str],
    "role": Required[str],
    "token": NotRequired[str],
    "caps": NotRequired[list[str]],
    "pubkey": NotRequired[bytes],
    "labels": NotRequired[dict[str, str]],
    "principal": NotRequired[str],
    "node": NotRequired[Optional["NodeInfo"]],
    "issued_at": NotRequired[int],
    "nonce": NotRequired[bytes],
    "proof": NotRequired[bytes],
}, total=False)

HelloOK = TypedDict("HelloOK", {
    "peer": Required[str],
    "caps": Required[list[str]],
    "server": NotRequired[str],
    "now": Required[int],
    "pubkey": NotRequired[bytes],
    "lease_sec": NotRequired[int],
    "controller_epoch": NotRequired[int],
    "subject": NotRequired[str],
    "tenant": NotRequired[str],
    "node_token": NotRequired[str],
}, total=False)

Idle = TypedDict("Idle", {
    "snapshot_every_sec": NotRequired[int],
    "destroy_after_sec": NotRequired[int],
}, total=False)

NetworkPolicy = TypedDict("NetworkPolicy", {
    "default": NotRequired[str],
    "rules": NotRequired[list["EgressRule"]],
}, total=False)

NodeDiag = TypedDict("NodeDiag", {
    "node": Required[str],
    "controller_epoch": NotRequired[int],
    "info": Required["NodeInfo"],
    "now": Required[int],
    "uptime_sec": Required[int],
    "data_dir": Required[str],
    "disk_free_bytes": Required[int],
    "disk_total_bytes": Required[int],
    "goroutines": Required[int],
    "heap_bytes": Required[int],
    "workspaces": NotRequired[list["WSDiag"]],
    "artifacts": Required[int],
    "artifact_bytes": NotRequired[int],
    "artifact_reserved_bytes": NotRequired[int],
    "artifact_reserved_objects": NotRequired[int],
    "artifact_max_bytes": NotRequired[int],
    "artifact_max_objects": NotRequired[int],
    "sessions_retained": NotRequired[int],
    "sessions_active": NotRequired[int],
    "sessions_max": NotRequired[int],
    "sessions_active_max": NotRequired[int],
    "sessions_per_workspace_max": NotRequired[int],
    "sessions_per_principal_max": NotRequired[int],
    "session_memory_bytes": NotRequired[int],
    "session_spill_bytes": NotRequired[int],
    "session_memory_chunks": NotRequired[int],
    "session_chunk_bytes": NotRequired[int],
    "requests_active_max": NotRequired[int],
    "connector_max_bytes": NotRequired[int],
    "connector_scope_max_bytes": NotRequired[int],
    "connector_object_max_bytes": NotRequired[int],
    "connector_max_objects": NotRequired[int],
    "connector_scope_max_objects": NotRequired[int],
    "mutation_records": NotRequired[int],
    "mutation_records_max": NotRequired[int],
    "snapshots_active": NotRequired[int],
    "snapshots_active_max": NotRequired[int],
    "volumes": NotRequired[int],
    "volume_attachments": NotRequired[int],
    "volume_source_bytes": NotRequired[int],
    "volume_source_max_bytes": NotRequired[int],
    "volume_source_entries": NotRequired[int],
    "volume_source_max_entries": NotRequired[int],
    "volume_quota_rejections": NotRequired[int],
    "metrics": NotRequired[dict[str, float]],
    "findings": NotRequired[list["Finding"]],
}, total=False)

NodeDiagReq = TypedDict("NodeDiagReq", {
    "ws": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
    "verify": NotRequired[bool],
}, total=False)

NodeInfo = TypedDict("NodeInfo", {
    "backends": Required[list[str]],
    "backend_descriptors": NotRequired[list["BackendDescriptor"]],
    "connectors": NotRequired[list[str]],
    "os": Required[str],
    "arch": Required[str],
    "cpu": Required[int],
    "mem_mib": Required[int],
    "caps": NotRequired[list[str]],
    "snapshots": NotRequired[str],
    "version": NotRequired[str],
}, total=False)

NodeListRes = TypedDict("NodeListRes", {
    "nodes": Required[list["NodeStatus"]],
}, total=False)

NodeStatus = TypedDict("NodeStatus", {
    "id": Required[str],
    "labels": NotRequired[dict[str, str]],
    "info": Required["NodeInfo"],
    "online": Required[bool],
    "last_seen": Required[int],
    "workspaces": NotRequired[list[str]],
    "protocol": NotRequired[list[str]],
}, total=False)

PeerBinding = TypedDict("PeerBinding", {
    "peer": Required[str],
    "key": Required[bytes],
    "tenant": NotRequired[str],
    "issued": NotRequired[int],
    "exp": Required[int],
    "sig": NotRequired[bytes],
}, total=False)

Placement = TypedDict("Placement", {
    "allow": NotRequired[dict[str, str]],
    "prefer": NotRequired[dict[str, str]],
    "node": NotRequired[str],
}, total=False)

Pool = TypedDict("Pool", {
    "spec": Required["PoolSpec"],
    "tenant": Required[str],
    "owner": Required[str],
    "current": Required[int],
    "created_at": Required[int],
    "updated_at": Required[int],
}, total=False)

PoolCreateReq = TypedDict("PoolCreateReq", {
    "spec": Required["PoolSpec"],
    "idem": NotRequired[str],
}, total=False)

PoolGetReq = TypedDict("PoolGetReq", {
    "name": Required[str],
}, total=False)

PoolListRes = TypedDict("PoolListRes", {
    "pools": Required[list["Pool"]],
}, total=False)

PoolRemoveReq = TypedDict("PoolRemoveReq", {
    "name": Required[str],
    "idem": NotRequired[str],
}, total=False)

PoolSpec = TypedDict("PoolSpec", {
    "name": Required[str],
    "vendor": Required[str],
    "min": Required[int],
    "max": Required[int],
    "labels": NotRequired[dict[str, str]],
    "backend": Required[str],
    "idle_scale_down_ms": NotRequired[int],
    "region": NotRequired[str],
    "size": NotRequired[str],
}, total=False)

PortOpenReq = TypedDict("PortOpenReq", {
    "ws": Required[str],
    "port": Required[int],
    "host": NotRequired[str],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

Principal = TypedDict("Principal", {
    "id": Required[str],
    "tenant": Required[str],
    "roles": Required[list[str]],
    "revision": Required[int],
    "created_at": Required[int],
    "updated_at": Required[int],
}, total=False)

PrincipalCreateReq = TypedDict("PrincipalCreateReq", {
    "tenant": NotRequired[str],
    "principal": Required[str],
    "roles": Required[list[str]],
    "idem": Required[str],
}, total=False)

PrincipalInviteReq = TypedDict("PrincipalInviteReq", {
    "tenant": Required[str],
    "principal": Required[str],
    "ttl_ms": Required[int],
    "idem": Required[str],
}, total=False)

PrincipalListReq = TypedDict("PrincipalListReq", {
    "tenant": NotRequired[str],
}, total=False)

PrincipalListRes = TypedDict("PrincipalListRes", {
    "principals": Required[list["Principal"]],
}, total=False)

PrincipalRevokeReq = TypedDict("PrincipalRevokeReq", {
    "tenant": NotRequired[str],
    "principal": Required[str],
    "idem": Required[str],
}, total=False)

PrincipalRevokeRes = TypedDict("PrincipalRevokeRes", {
    "revision": Required[int],
}, total=False)

PrincipalTokenIssueReq = TypedDict("PrincipalTokenIssueReq", {
    "tenant": NotRequired[str],
    "principal": Required[str],
    "role": Required[str],
    "ttl_ms": Required[int],
    "idem": Required[str],
}, total=False)

PrincipalTokenIssueRes = TypedDict("PrincipalTokenIssueRes", {
    "access_token": Required[str],
    "expires_at": Required[int],
}, total=False)

Queue = TypedDict("Queue", {
    "id": Required[str],
    "ws": Required[str],
    "tenant": Required[str],
    "owner": Required[str],
    "recipe": NotRequired[str],
    "items": Required[list["QueueItem"]],
    "cursor": Required[int],
    "status": Required[str],
    "sleep_after_sec": NotRequired[int],
    "sleep_until": NotRequired[str],
    "created_at": Required[int],
    "updated_at": Required[int],
}, total=False)

QueueAdvanceReq = TypedDict("QueueAdvanceReq", {
    "id": Required[str],
    "index": Required[int],
    "session": NotRequired[str],
    "exit": Required[int],
    "signal": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

QueueCreateReq = TypedDict("QueueCreateReq", {
    "ws": Required[str],
    "recipe": NotRequired[str],
    "tasks": Required[list[str]],
    "sleep_after_sec": NotRequired[int],
    "sleep_until": NotRequired[str],
    "idem": NotRequired[str],
}, total=False)

QueueGetReq = TypedDict("QueueGetReq", {
    "id": Required[str],
}, total=False)

QueueItem = TypedDict("QueueItem", {
    "task": Required[str],
    "session": NotRequired[str],
    "exit": NotRequired[int],
    "signal": NotRequired[str],
    "attempts": NotRequired[int],
    "finished_at": NotRequired[int],
}, total=False)

QueueListReq = TypedDict("QueueListReq", {
    "ws": NotRequired[str],
}, total=False)

QueueListRes = TypedDict("QueueListRes", {
    "queues": Required[list["Queue"]],
}, total=False)

RepoSpec = TypedDict("RepoSpec", {
    "url": NotRequired[str],
    "ref": NotRequired[str],
    "depth": NotRequired[int],
    "branch": NotRequired[str],
}, total=False)

Requires = TypedDict("Requires", {
    "cpu": NotRequired[int],
    "mem_mib": NotRequired[int],
    "backend": NotRequired[str],
    "caps": NotRequired[list[str]],
    "os": NotRequired[str],
    "arch": NotRequired[str],
}, total=False)

RunInfo = TypedDict("RunInfo", {
    "recipe": Required[str],
    "task_hash": NotRequired[str],
    "sandbox": NotRequired[str],
    "auth": NotRequired[str],
}, total=False)

RuntimeCaps = TypedDict("RuntimeCaps", {
    "snapshots": Required[str],
    "display": NotRequired[bool],
    "mount_path": NotRequired[bool],
}, total=False)

SAckReq = TypedDict("SAckReq", {
    "s": Required[str],
    "seq": Required[int],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SAttachReq = TypedDict("SAttachReq", {
    "s": Required[str],
    "from": Required[int],
    "subscription": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SCloseReq = TypedDict("SCloseReq", {
    "s": Required[str],
    "kill": NotRequired[bool],
    "subscription": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SInputReq = TypedDict("SInputReq", {
    "s": Required[str],
    "iseq": Required[int],
    "d": NotRequired[bytes],
    "eof": NotRequired[bool],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SListReq = TypedDict("SListReq", {
    "ws": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SListRes = TypedDict("SListRes", {
    "sessions": Required[list["SessionStatus"]],
}, total=False)

SOpenReq = TypedDict("SOpenReq", {
    "ws": Required[str],
    "kind": Required[str],
    "program": Required[list[str]],
    "cwd": NotRequired[str],
    "env": NotRequired[dict[str, str]],
    "rows": NotRequired[int],
    "cols": NotRequired[int],
    "stdin": Required[bool],
    "timeout_sec": NotRequired[int],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
    "no_sub": NotRequired[bool],
    "run": NotRequired[Optional["RunInfo"]],
}, total=False)

SOpenRes = TypedDict("SOpenRes", {
    "s": Required[str],
    "next": Required[int],
    "last_iseq": NotRequired[int],
}, total=False)

SResizeReq = TypedDict("SResizeReq", {
    "s": Required[str],
    "rows": Required[int],
    "cols": Required[int],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SSignalReq = TypedDict("SSignalReq", {
    "s": Required[str],
    "signal": Required[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SWaitReq = TypedDict("SWaitReq", {
    "s": Required[str],
    "timeout_sec": NotRequired[int],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

SWaitRes = TypedDict("SWaitRes", {
    "exited": Required[bool],
    "exit": NotRequired[Optional["ExitInfo"]],
}, total=False)

SecuritySpec = TypedDict("SecuritySpec", {
    "profile": NotRequired[str],
    "min_isolation": NotRequired[str],
    "require_sibling_isolation": NotRequired[bool],
    "require_enforced_egress": NotRequired[bool],
    "secret_mode": NotRequired[str],
    "network": NotRequired["NetworkPolicy"],
    "audit": NotRequired["AuditPolicy"],
}, total=False)

SessionCapabilityCheckReq = TypedDict("SessionCapabilityCheckReq", {
    "ws": Required[str],
    "gen": Required[int],
    "capability": Required[str],
}, total=False)

SessionCapabilityCheckRes = TypedDict("SessionCapabilityCheckRes", {
    "principal": Required[str],
    "tenant": Required[str],
}, total=False)

SessionCapabilityIssueReq = TypedDict("SessionCapabilityIssueReq", {
    "client": Required[str],
    "ws": Required[str],
    "gen": Required[int],
    "authz_revision": Required[int],
    "principal": Required[str],
    "tenant": Required[str],
    "roles": NotRequired[list[str]],
}, total=False)

SessionCapabilityIssueRes = TypedDict("SessionCapabilityIssueRes", {
    "capability": Required[str],
    "expires_at": Required[int],
}, total=False)

SessionCapabilityRenewReq = TypedDict("SessionCapabilityRenewReq", {
    "ws": Required[str],
    "gen": Required[int],
    "capability": Required[str],
}, total=False)

SessionInfo = TypedDict("SessionInfo", {
    "id": Required[str],
    "ws": Required[str],
    "kind": Required[str],
    "program": NotRequired[list[str]],
    "pid": NotRequired[int],
    "opened_at": Required[int],
    "run": NotRequired[Optional["RunInfo"]],
}, total=False)

SessionLogCommitReq = TypedDict("SessionLogCommitReq", {
    "session": Required[str],
    "workspace": Required[str],
    "gen": Required[int],
    "principal": Required[str],
    "kind": Required[str],
    "info": NotRequired["SessionInfo"],
    "exit": NotRequired["ExitInfo"],
    "max_chunk": Required[int],
    "segments": NotRequired[list["SessionLogSegment"]],
    "complete": NotRequired[bool],
}, total=False)

SessionLogGetReq = TypedDict("SessionLogGetReq", {
    "session": Required[str],
    "workspace": Required[str],
    "gen": Required[int],
}, total=False)

SessionLogRecord = TypedDict("SessionLogRecord", {
    "session": Required[str],
    "workspace": Required[str],
    "tenant": Required[str],
    "principal": Required[str],
    "kind": Required[str],
    "info": Required["SessionInfo"],
    "exit": Required["ExitInfo"],
    "max_chunk": Required[int],
    "segments": NotRequired[list["SessionLogSegment"]],
    "complete": NotRequired[bool],
    "updated_at": Required[int],
    "expires_at": NotRequired[int],
}, total=False)

SessionLogSegment = TypedDict("SessionLogSegment", {
    "first": Required[int],
    "next": Required[int],
    "artifact": Required[str],
    "bytes": Required[int],
}, total=False)

SessionStatus = TypedDict("SessionStatus", {
    "info": Required["SessionInfo"],
    "exited": Required[bool],
    "exit": NotRequired[Optional["ExitInfo"]],
    "next": Required[int],
    "oldest": Required[int],
    "blob_bytes": NotRequired[int],
    "blob_segments": NotRequired[int],
    "unavailable_tier": NotRequired[str],
}, total=False)

Tenant = TypedDict("Tenant", {
    "id": Required[str],
    "state": Required[str],
    "revision": Required[int],
    "policy": Required["TenantPolicy"],
    "created_at": Required[int],
    "updated_at": Required[int],
}, total=False)

TenantCreateReq = TypedDict("TenantCreateReq", {
    "id": Required[str],
    "policy": Required["TenantPolicy"],
    "idem": Required[str],
}, total=False)

TenantGetReq = TypedDict("TenantGetReq", {
    "id": Required[str],
}, total=False)

TenantListRes = TypedDict("TenantListRes", {
    "tenants": Required[list["Tenant"]],
}, total=False)

TenantOIDC = TypedDict("TenantOIDC", {
    "issuer": NotRequired[str],
    "client_id": NotRequired[str],
    "audience": NotRequired[str],
    "scopes": NotRequired[list[str]],
    "group_roles": NotRequired[dict[str, list[str]]],
    "tenant_claim": NotRequired[str],
    "groups_claim": NotRequired[str],
}, total=False)

TenantPolicy = TypedDict("TenantPolicy", {
    "quotas": Required["TenantQuotas"],
    "retention": Required["TenantRetention"],
    "residency": Required["TenantResidency"],
    "oidc": Required["TenantOIDC"],
    "stripe_customer_id": NotRequired[str],
}, total=False)

TenantQuotas = TypedDict("TenantQuotas", {
    "max_workspaces": Required[int],
    "max_nodes": Required[int],
    "max_artifact_bytes": Required[int],
    "max_active_sessions": Required[int],
}, total=False)

TenantResidency = TypedDict("TenantResidency", {
    "allowed_regions": NotRequired[list[str]],
    "required_labels": NotRequired[dict[str, str]],
}, total=False)

TenantRetention = TypedDict("TenantRetention", {
    "events_ms": Required[int],
    "session_logs_ms": Required[int],
    "artifacts_ms": Required[int],
    "meter_events_ms": Required[int],
}, total=False)

TenantStateReq = TypedDict("TenantStateReq", {
    "id": Required[str],
    "state": Required[str],
    "expected_revision": Required[int],
    "idem": Required[str],
}, total=False)

TenantUpdateReq = TypedDict("TenantUpdateReq", {
    "id": Required[str],
    "policy": Required["TenantPolicy"],
    "expected_revision": Required[int],
    "idem": Required[str],
}, total=False)

TenantUsage = TypedDict("TenantUsage", {
    "workspaces": Required[int],
    "nodes": Required[int],
    "artifact_bytes": Required[int],
    "active_sessions": Required[int],
}, total=False)

TenantUsageReq = TypedDict("TenantUsageReq", {
    "tenant": NotRequired[str],
}, total=False)

Timer = TypedDict("Timer", {
    "id": Required[str],
    "ws": Required[str],
    "at": NotRequired[int],
    "on": NotRequired[str],
    "match": NotRequired[dict[str, str]],
    "action": Required[str],
    "fired": Required[bool],
    "fired_at": NotRequired[int],
    "created_at": Required[int],
}, total=False)

TimerListRes = TypedDict("TimerListRes", {
    "timers": Required[list["Timer"]],
}, total=False)

TranscriptChunk = TypedDict("TranscriptChunk", {
    "seq": Required[int],
    "stream": Required[int],
    "at": Required[int],
    "data": Required[bytes],
}, total=False)

TranscriptGap = TypedDict("TranscriptGap", {
    "from": Required[int],
    "to": Required[int],
}, total=False)

TranscriptRecord = TypedDict("TranscriptRecord", {
    "index": Required[int],
    "run": Required[str],
    "seq": Required[int],
    "stream": Required[int],
    "at": Required[int],
    "data": Required[bytes],
}, total=False)

Usage = TypedDict("Usage", {
    "budget_id": Required[str],
    "window": Required[str],
    "since": Required[int],
    "requests": Required[int],
    "tokens": Required[int],
    "estimated_cost_micros": Required[int],
    "active_reservations": Required[int],
    "unmetered_requests": Required[int],
    "incomplete_requests": Required[int],
}, total=False)

UsageReq = TypedDict("UsageReq", {
    "tenant": NotRequired[str],
    "ws": NotRequired[str],
    "principal": NotRequired[str],
    "binding": NotRequired[str],
    "window": NotRequired[str],
}, total=False)

UsageRes = TypedDict("UsageRes", {
    "usage": Required[list["Usage"]],
}, total=False)

Volume = TypedDict("Volume", {
    "id": Required[str],
    "tenant": Required[str],
    "owner": Required[str],
    "artifact": Required[str],
    "version": Required[int],
    "versions": Required[list["VolumeVersion"]],
    "created_at": Required[int],
    "updated_at": Required[int],
}, total=False)

VolumeArchiveReq = TypedDict("VolumeArchiveReq", {
    "ws": Required[str],
    "path": Required[str],
    "upload": Required[bool],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

VolumeAttachReq = TypedDict("VolumeAttachReq", {
    "id": Required[str],
    "ws": Required[str],
    "generation": Required[int],
    "path": Required[str],
    "idem": NotRequired[str],
}, total=False)

VolumeCreateReq = TypedDict("VolumeCreateReq", {
    "id": Required[str],
    "artifact": Required[str],
    "idem": NotRequired[str],
}, total=False)

VolumeDetachReq = TypedDict("VolumeDetachReq", {
    "ws": Required[str],
    "generation": Required[int],
    "path": Required[str],
    "idem": NotRequired[str],
}, total=False)

VolumeGetReq = TypedDict("VolumeGetReq", {
    "id": Required[str],
}, total=False)

VolumeListRes = TypedDict("VolumeListRes", {
    "volumes": Required[list["Volume"]],
}, total=False)

VolumeMount = TypedDict("VolumeMount", {
    "id": Required[str],
    "path": Required[str],
    "version": NotRequired[int],
    "artifact": NotRequired[str],
}, total=False)

VolumePublishPathReq = TypedDict("VolumePublishPathReq", {
    "ws": Required[str],
    "path": Required[str],
    "volume": Required[str],
    "expected_version": Required[int],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

VolumePublishReq = TypedDict("VolumePublishReq", {
    "id": Required[str],
    "ws": Required[str],
    "generation": Required[int],
    "artifact": Required[str],
    "expected_version": Required[int],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

VolumeRemoveReq = TypedDict("VolumeRemoveReq", {
    "id": Required[str],
    "idem": NotRequired[str],
}, total=False)

VolumeVersion = TypedDict("VolumeVersion", {
    "number": Required[int],
    "artifact": Required[str],
    "published_by": NotRequired[str],
    "generation": NotRequired[int],
    "published_at": Required[int],
}, total=False)

WSACLReq = TypedDict("WSACLReq", {
    "id": Required[str],
    "acl": Required["WorkspaceACL"],
    "idem": NotRequired[str],
}, total=False)

WSClaimReq = TypedDict("WSClaimReq", {
    "id": Required[str],
}, total=False)

WSClaimRes = TypedDict("WSClaimRes", {
    "workspace": Required["Workspace"],
    "lease_sec": Required[int],
}, total=False)

WSCreateReq = TypedDict("WSCreateReq", {
    "spec": Required["WorkspaceSpec"],
    "idem": NotRequired[str],
}, total=False)

WSDiag = TypedDict("WSDiag", {
    "id": Required[str],
    "gen": Required[int],
    "backend": Required[str],
    "root": Required[str],
    "volumes": NotRequired[list["VolumeMount"]],
    "bytes": Required[int],
    "files": Required[int],
    "broker": NotRequired[str],
    "bindings": NotRequired[list[str]],
    "lease_ends": NotRequired[int],
    "sessions": NotRequired[list["SessionStatus"]],
}, total=False)

WSGetReq = TypedDict("WSGetReq", {
    "id": Required[str],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
}, total=False)

WSInfoRes = TypedDict("WSInfoRes", {
    "ws": Required[str],
    "backend": Required[str],
    "root": NotRequired[str],
    "sessions": NotRequired[list[str]],
    "broker": NotRequired[str],
}, total=False)

WSListRes = TypedDict("WSListRes", {
    "workspaces": Required[list["Workspace"]],
}, total=False)

WSMoveReq = TypedDict("WSMoveReq", {
    "id": Required[str],
    "requires": NotRequired[Optional["Requires"]],
    "placement": NotRequired[Optional["Placement"]],
    "idem": NotRequired[str],
}, total=False)

WSQuarantineCommitReq = TypedDict("WSQuarantineCommitReq", {
    "operation": Required[str],
    "ws": Required[str],
    "gen": Required[int],
    "backend": Required[str],
    "snapshot": Required[str],
    "snapshot_format": NotRequired[str],
}, total=False)

WSQuarantineReq = TypedDict("WSQuarantineReq", {
    "operation": Required[str],
    "ws": Required[str],
    "gen": Required[int],
    "action": Required[str],
    "backend": NotRequired[str],
    "exclude": NotRequired[list[str]],
    "security": NotRequired["SecuritySpec"],
    "tenant": NotRequired[str],
    "volumes": NotRequired[list["VolumeMount"]],
}, total=False)

WSQuarantineRes = TypedDict("WSQuarantineRes", {
    "fenced": Required[bool],
    "gen": Required[int],
    "action": Required[str],
    "backend": NotRequired[str],
    "snapshot": NotRequired[str],
    "snapshot_format": NotRequired[str],
    "warning": NotRequired[str],
}, total=False)

WSReadyReq = TypedDict("WSReadyReq", {
    "id": Required[str],
    "gen": Required[int],
    "restore_processes": NotRequired[str],
}, total=False)

WSReleaseCommitReq = TypedDict("WSReleaseCommitReq", {
    "id": Required[str],
    "gen": Required[int],
    "operation": NotRequired[str],
    "snapshot": NotRequired[str],
    "snapshot_format": NotRequired[str],
}, total=False)

WSReleaseReq = TypedDict("WSReleaseReq", {
    "ws": Required[str],
    "gen": Required[int],
    "release_epoch": NotRequired[int],
    "operation": NotRequired[str],
    "snapshot": Required[bool],
    "reason": NotRequired[str],
    "tenant": NotRequired[str],
    "backend": NotRequired[str],
    "spec": NotRequired["WorkspaceSpec"],
}, total=False)

WSReleasedReq = TypedDict("WSReleasedReq", {
    "id": Required[str],
    "gen": Required[int],
    "operation": NotRequired[str],
    "snapshot": NotRequired[str],
    "snapshot_format": NotRequired[str],
    "reason": NotRequired[str],
    "failed": NotRequired[bool],
    "preparing": NotRequired[bool],
}, total=False)

WSRenewReq = TypedDict("WSRenewReq", {
    "ids": Required[list[str]],
    "gen": NotRequired[dict[str, int]],
    "controller_epoch": NotRequired[int],
    "authz": NotRequired[dict[str, int]],
}, total=False)

WSRenewRes = TypedDict("WSRenewRes", {
    "results": Required[list["WSRenewResult"]],
    "controller_epoch": NotRequired[int],
}, total=False)

WSRenewResult = TypedDict("WSRenewResult", {
    "id": Required[str],
    "gen": Required[int],
    "accepted": Required[bool],
    "authoritative_gen": NotRequired[int],
    "lease_until": NotRequired[int],
    "action": Required[str],
    "controller_epoch": NotRequired[int],
    "authz_revision": NotRequired[int],
    "revoked": NotRequired[list[str]],
    "authz_reset": NotRequired[bool],
}, total=False)

WSSleepReq = TypedDict("WSSleepReq", {
    "id": Required[str],
    "after_sec": NotRequired[int],
    "at": NotRequired[int],
    "on": NotRequired[str],
    "match": NotRequired[dict[str, str]],
    "idem": NotRequired[str],
}, total=False)

WSSnapshotCommitReq = TypedDict("WSSnapshotCommitReq", {
    "id": Required[str],
    "gen": Required[int],
    "snapshot": Required[str],
    "format": NotRequired[str],
}, total=False)

WSSnapshotReq = TypedDict("WSSnapshotReq", {
    "ws": Required[str],
    "upload": Required[bool],
    "authoritative": NotRequired[bool],
    "idem": NotRequired[str],
    "grant": NotRequired[Optional["Grant"]],
    "gen": NotRequired[int],
}, total=False)

WSSnapshotRes = TypedDict("WSSnapshotRes", {
    "artifact": Required[str],
    "bytes": Required[int],
    "consistency": Required[str],
    "authoritative": Required[bool],
    "format": NotRequired[str],
    "uploaded_bytes": NotRequired[int],
    "chunks": NotRequired[int],
    "uploaded_chunks": NotRequired[int],
}, total=False)

Workspace = TypedDict("Workspace", {
    "id": Required[str],
    "spec": Required["WorkspaceSpec"],
    "state": Required[str],
    "node": NotRequired[str],
    "lease_until": NotRequired[int],
    "last_snapshot": NotRequired[str],
    "last_snapshot_format": NotRequired[str],
    "last_snapshot_objects": NotRequired[list[str]],
    "created_at": Required[int],
    "updated_at": Required[int],
    "gen": Required[int],
    "tenant": NotRequired[str],
    "owner": NotRequired[str],
    "authz_revision": NotRequired[int],
    "revocations": NotRequired[list["AuthzRevocation"]],
    "revocation_floor": NotRequired[int],
    "release_epoch": NotRequired[int],
    "release_operation": NotRequired[str],
    "quarantine_operation": NotRequired[str],
    "quarantined_at": NotRequired[int],
}, total=False)

WorkspaceACL = TypedDict("WorkspaceACL", {
    "readers": NotRequired[list[str]],
    "writers": NotRequired[list[str]],
}, total=False)

WorkspaceSelector = TypedDict("WorkspaceSelector", {
    "all": NotRequired[bool],
    "workspace": NotRequired[str],
    "tenant": NotRequired[str],
    "principal": NotRequired[str],
    "run": NotRequired[str],
    "node": NotRequired[str],
    "model": NotRequired[str],
    "backend": NotRequired[str],
    "labels": NotRequired[dict[str, str]],
    "created_after": NotRequired[int],
    "created_before": NotRequired[int],
}, total=False)

WorkspaceSpec = TypedDict("WorkspaceSpec", {
    "name": NotRequired[str],
    "run": NotRequired[str],
    "model": NotRequired[str],
    "labels": NotRequired[dict[str, str]],
    "image": NotRequired[str],
    "restore_from": NotRequired[str],
    "restore_format": NotRequired[str],
    "restore_objects": NotRequired[list[str]],
    "base": NotRequired[str],
    "requires": Required["Requires"],
    "placement": Required["Placement"],
    "bindings": NotRequired[list[str]],
    "env": NotRequired[dict[str, str]],
    "principal": NotRequired[str],
    "idle": Required["Idle"],
    "exclude": NotRequired[list[str]],
    "security": NotRequired["SecuritySpec"],
    "acl": NotRequired["WorkspaceACL"],
    "mount_path": NotRequired[str],
    "repo": NotRequired["RepoSpec"],
    "volumes": NotRequired[list["VolumeMount"]],
}, total=False)

OPERATIONS: dict[str, dict[str, object]] = {
    "agent.approval.decided": {"constant": "OpAgentApprovalDecided", "request": "AgentApprovalDecidedReq", "response": ""},
    "agent.cancel": {"constant": "OpAgentCancel", "request": "AgentGetReq", "response": "Agent"},
    "agent.create": {"constant": "OpAgentCreate", "request": "AgentCreateReq", "response": "Agent"},
    "agent.deliver": {"constant": "OpAgentDeliver", "request": "AgentDeliverReq", "response": ""},
    "agent.destroy": {"constant": "OpAgentDestroy", "request": "AgentGetReq", "response": ""},
    "agent.fork": {"constant": "OpAgentFork", "request": "AgentForkReq", "response": "Agent"},
    "agent.get": {"constant": "OpAgentGet", "request": "AgentGetReq", "response": "Agent"},
    "agent.list": {"constant": "OpAgentList", "request": "AgentListReq", "response": "AgentListRes"},
    "agent.message": {"constant": "OpAgentMessage", "request": "AgentMessageReq", "response": "AgentMessageRes"},
    "agent.report": {"constant": "OpAgentReport", "request": "AgentReport", "response": ""},
    "agent.run": {"constant": "OpAgentRun", "request": "AgentRunReq", "response": "AgentRunRes"},
    "agent.run.cancel": {"constant": "OpAgentRunCancel", "request": "AgentRunCancelReq", "response": ""},
    "agent.sleep": {"constant": "OpAgentSleep", "request": "AgentGetReq", "response": "Agent"},
    "agent.transcript": {"constant": "OpAgentTranscript", "request": "AgentTranscriptReq", "response": "AgentTranscriptRes"},
    "agent.wake": {"constant": "OpAgentWake", "request": "AgentWakeReq", "response": "Agent"},
    "approval.decide": {"constant": "OpApprovalDecide", "request": "ApprovalDecideReq", "response": "Approval"},
    "approval.get": {"constant": "OpApprovalGet", "request": "ApprovalGetReq", "response": "Approval"},
    "approval.list": {"constant": "OpApprovalList", "request": "ApprovalListReq", "response": "ApprovalListRes"},
    "artifact.proof": {"constant": "OpArtifactProof", "request": "ArtifactProofReq", "response": "ArtifactProofRes"},
    "audit.export": {"constant": "OpAuditExport", "request": "AuditExportReq", "response": "AuditExportRes"},
    "audit.key": {"constant": "OpAuditKey", "request": "AuditKeyReq", "response": "AuditKeyRes"},
    "base.create": {"constant": "OpBaseCreate", "request": "BaseCreateReq", "response": "Base"},
    "base.list": {"constant": "OpBaseList", "request": "", "response": "BaseListRes"},
    "base.remove": {"constant": "OpBaseRemove", "request": "BaseRemoveReq", "response": ""},
    "binding.lease": {"constant": "OpBindingLease", "request": "BindingLeaseReq", "response": "BindingLeaseRes"},
    "budget.create": {"constant": "OpBudgetCreate", "request": "BudgetCreateReq", "response": "Budget"},
    "budget.list": {"constant": "OpBudgetList", "request": "BudgetListReq", "response": "BudgetListRes"},
    "budget.remove": {"constant": "OpBudgetRemove", "request": "BudgetRemoveReq", "response": ""},
    "budget.reserve": {"constant": "OpBudgetReserve", "request": "BudgetReserveReq", "response": "BudgetReservation"},
    "budget.settle": {"constant": "OpBudgetSettle", "request": "BudgetSettleReq", "response": "BudgetSettlement"},
    "controller.state": {"constant": "OpControllerState", "request": "", "response": ""},
    "diag": {"constant": "OpDiag", "request": "DiagReq", "response": "ControlDiag"},
    "e2ee.kx": {"constant": "OpE2EEKeyExchange", "request": "", "response": ""},
    "e2ee.sealed": {"constant": "OpE2EESealed", "request": "", "response": ""},
    "egress.approval": {"constant": "OpEgressApproval", "request": "EgressApprovalReq", "response": "EgressApprovalRes"},
    "events.post": {"constant": "OpEventsPost", "request": "EventPost", "response": ""},
    "events.stop": {"constant": "OpEventsStop", "request": "EventsStopReq", "response": ""},
    "events.tail": {"constant": "OpEventsTail", "request": "EventsTailReq", "response": ""},
    "fleet.get": {"constant": "OpFleetGet", "request": "FleetGetReq", "response": "FleetOperation"},
    "fleet.list": {"constant": "OpFleetList", "request": "", "response": "FleetListRes"},
    "fleet.quarantine": {"constant": "OpFleetQuarantine", "request": "FleetQuarantineReq", "response": "FleetOperation"},
    "fs.apply_tar": {"constant": "OpFSApplyTar", "request": "FSApplyTarReq", "response": "FSApplyTarRes"},
    "fs.edit": {"constant": "OpFSEdit", "request": "FSEditReq", "response": "FSEditRes"},
    "fs.list": {"constant": "OpFSList", "request": "FSListReq", "response": "FSListRes"},
    "fs.mkdir": {"constant": "OpFSMkdir", "request": "FSMkdirReq", "response": ""},
    "fs.read": {"constant": "OpFSRead", "request": "FSReadReq", "response": "FSReadRes"},
    "fs.remove": {"constant": "OpFSRemove", "request": "FSRemoveReq", "response": ""},
    "fs.rename": {"constant": "OpFSRename", "request": "FSRenameReq", "response": ""},
    "fs.search": {"constant": "OpFSSearch", "request": "FSSearchReq", "response": "FSSearchRes"},
    "fs.stat": {"constant": "OpFSStat", "request": "", "response": "FSStatRes"},
    "fs.write": {"constant": "OpFSWrite", "request": "FSWriteReq", "response": ""},
    "grant": {"constant": "OpGrant", "request": "GrantReq", "response": "Grant"},
    "node.diag": {"constant": "OpNodeDiag", "request": "NodeDiagReq", "response": "NodeDiag"},
    "node.list": {"constant": "OpNodeList", "request": "", "response": "NodeListRes"},
    "node.status": {"constant": "OpNodeStatus", "request": "", "response": "NodeStatus"},
    "pool.create": {"constant": "OpPoolCreate", "request": "PoolCreateReq", "response": "Pool"},
    "pool.get": {"constant": "OpPoolGet", "request": "PoolGetReq", "response": "Pool"},
    "pool.list": {"constant": "OpPoolList", "request": "", "response": "PoolListRes"},
    "pool.remove": {"constant": "OpPoolRemove", "request": "PoolRemoveReq", "response": ""},
    "port.open": {"constant": "OpPortOpen", "request": "PortOpenReq", "response": "SOpenRes"},
    "principal.create": {"constant": "OpPrincipalCreate", "request": "PrincipalCreateReq", "response": ""},
    "principal.invite": {"constant": "OpPrincipalInvite", "request": "PrincipalInviteReq", "response": ""},
    "principal.list": {"constant": "OpPrincipalList", "request": "PrincipalListReq", "response": "PrincipalListRes"},
    "principal.revoke": {"constant": "OpPrincipalRevoke", "request": "PrincipalRevokeReq", "response": "PrincipalRevokeRes"},
    "principal.token.issue": {"constant": "OpPrincipalTokenIssue", "request": "PrincipalTokenIssueReq", "response": "PrincipalTokenIssueRes"},
    "queue.advance": {"constant": "OpQueueAdvance", "request": "QueueAdvanceReq", "response": "Queue"},
    "queue.create": {"constant": "OpQueueCreate", "request": "QueueCreateReq", "response": "Queue"},
    "queue.get": {"constant": "OpQueueGet", "request": "QueueGetReq", "response": "Queue"},
    "queue.list": {"constant": "OpQueueList", "request": "QueueListReq", "response": "QueueListRes"},
    "s.ack": {"constant": "OpSAck", "request": "SAckReq", "response": ""},
    "s.attach": {"constant": "OpSAttach", "request": "SAttachReq", "response": "SOpenRes"},
    "s.close": {"constant": "OpSClose", "request": "SCloseReq", "response": ""},
    "s.input": {"constant": "OpSInput", "request": "SInputReq", "response": ""},
    "s.list": {"constant": "OpSList", "request": "SListReq", "response": "SListRes"},
    "s.open": {"constant": "OpSOpen", "request": "SOpenReq", "response": "SOpenRes"},
    "s.resize": {"constant": "OpSResize", "request": "SResizeReq", "response": ""},
    "s.signal": {"constant": "OpSSignal", "request": "SSignalReq", "response": ""},
    "s.wait": {"constant": "OpSWait", "request": "SWaitReq", "response": "SWaitRes"},
    "session.cap.check": {"constant": "OpSessionCapabilityCheck", "request": "SessionCapabilityCheckReq", "response": "SessionCapabilityCheckRes"},
    "session.cap.issue": {"constant": "OpSessionCapabilityIssue", "request": "SessionCapabilityIssueReq", "response": "SessionCapabilityIssueRes"},
    "session.cap.renew": {"constant": "OpSessionCapabilityRenew", "request": "SessionCapabilityRenewReq", "response": ""},
    "session.log.commit": {"constant": "OpSessionLogCommit", "request": "SessionLogCommitReq", "response": ""},
    "session.log.delete": {"constant": "OpSessionLogDelete", "request": "", "response": ""},
    "session.log.get": {"constant": "OpSessionLogGet", "request": "SessionLogGetReq", "response": ""},
    "tenant.create": {"constant": "OpTenantCreate", "request": "TenantCreateReq", "response": ""},
    "tenant.get": {"constant": "OpTenantGet", "request": "TenantGetReq", "response": ""},
    "tenant.list": {"constant": "OpTenantList", "request": "", "response": "TenantListRes"},
    "tenant.state": {"constant": "OpTenantState", "request": "TenantStateReq", "response": ""},
    "tenant.update": {"constant": "OpTenantUpdate", "request": "TenantUpdateReq", "response": ""},
    "tenant.usage": {"constant": "OpTenantUsage", "request": "TenantUsageReq", "response": ""},
    "timer.list": {"constant": "OpTimerList", "request": "", "response": "TimerListRes"},
    "usage.get": {"constant": "OpUsageGet", "request": "UsageReq", "response": "UsageRes"},
    "volume.archive": {"constant": "OpVolumeArchive", "request": "VolumeArchiveReq", "response": "WSSnapshotRes"},
    "volume.attach": {"constant": "OpVolumeAttach", "request": "VolumeAttachReq", "response": "Workspace"},
    "volume.create": {"constant": "OpVolumeCreate", "request": "VolumeCreateReq", "response": "Volume"},
    "volume.detach": {"constant": "OpVolumeDetach", "request": "VolumeDetachReq", "response": "Workspace"},
    "volume.get": {"constant": "OpVolumeGet", "request": "VolumeGetReq", "response": "Volume"},
    "volume.list": {"constant": "OpVolumeList", "request": "", "response": "VolumeListRes"},
    "volume.publish": {"constant": "OpVolumePublish", "request": "VolumePublishReq", "response": ""},
    "volume.publish.commit": {"constant": "OpVolumePublishCommit", "request": "", "response": ""},
    "volume.remove": {"constant": "OpVolumeRemove", "request": "VolumeRemoveReq", "response": ""},
    "ws.acl": {"constant": "OpWSACL", "request": "WSACLReq", "response": "Workspace"},
    "ws.claim": {"constant": "OpWSClaim", "request": "WSClaimReq", "response": "WSClaimRes"},
    "ws.create": {"constant": "OpWSCreate", "request": "WSCreateReq", "response": "Workspace"},
    "ws.destroy": {"constant": "OpWSDestroy", "request": "WSGetReq", "response": ""},
    "ws.get": {"constant": "OpWSGet", "request": "WSGetReq", "response": "Workspace"},
    "ws.info": {"constant": "OpWSInfo", "request": "WSGetReq", "response": "WSInfoRes"},
    "ws.list": {"constant": "OpWSList", "request": "", "response": "WSListRes"},
    "ws.move": {"constant": "OpWSMove", "request": "WSMoveReq", "response": "Workspace"},
    "ws.quarantine": {"constant": "OpWSQuarantine", "request": "WSQuarantineReq", "response": "WSQuarantineRes"},
    "ws.quarantine.commit": {"constant": "OpWSQuarantineCommit", "request": "WSQuarantineCommitReq", "response": ""},
    "ws.ready": {"constant": "OpWSReady", "request": "WSReadyReq", "response": ""},
    "ws.release": {"constant": "OpWSRelease", "request": "WSReleaseReq", "response": ""},
    "ws.release.abort": {"constant": "OpWSReleaseAbort", "request": "", "response": ""},
    "ws.release.abort.commit": {"constant": "OpWSReleaseAbortCommit", "request": "", "response": ""},
    "ws.release.commit": {"constant": "OpWSReleaseCommit", "request": "WSReleaseCommitReq", "response": ""},
    "ws.released": {"constant": "OpWSReleased", "request": "WSReleasedReq", "response": ""},
    "ws.renew": {"constant": "OpWSRenew", "request": "WSRenewReq", "response": "WSRenewRes"},
    "ws.sleep": {"constant": "OpWSSleep", "request": "WSSleepReq", "response": "Timer"},
    "ws.snapshot": {"constant": "OpWSSnapshot", "request": "WSSnapshotReq", "response": "WSSnapshotRes"},
    "ws.snapshot.commit": {"constant": "OpWSSnapshotCommit", "request": "WSSnapshotCommitReq", "response": ""},
    "ws.wake": {"constant": "OpWSWake", "request": "WSGetReq", "response": "Workspace"},
}
