#!/bin/sh
# gen-llms.sh — write llms.txt and llms-full.txt from the docs that already
# exist, so the two files can never drift from README.md, docs/tutorial.md and
# docs/harness-integration.md. `make docs` runs it; `make lint` fails when the
# committed output is stale.
#
# llms.txt follows llmstxt.org: an H1, a blockquote summary, then sections of
# `- [title](url): one line` entries. Each entry's line is the first paragraph
# under the matching heading, which keeps the index honest: if a section says
# nothing useful in its first sentence, it shows here.
set -eu

cd "$(dirname "$0")/.."
BASE=${LLMS_BASE_URL:-https://github.com/remount-dev/remount/blob/main}

first_para() {
	# first_para FILE HEADING: the first sentence of the first prose paragraph
	# after HEADING, joined onto one line. Code, tables and lists are skipped.
	awk -v h="$2" '
		function flush() {
			if (done || para == "") return
			if (match(para, /[.!?]([ ]|$)/)) para = substr(para, 1, RSTART)
			print para; done = 1; exit
		}
		found && /^```/ { if (!incode) flush(); incode = !incode; next }
		found && incode { next }
		found && /^#/ { flush(); exit }
		found && /^[[:space:]]*$/ { flush(); next }
		found && (/^\|/ || /^[-*] / || /^[0-9]+\. /) { flush(); next }
		found { gsub(/^[[:space:]]+|[[:space:]]+$/, ""); para = (para == "" ? $0 : para " " $0); next }
		$0 == h { found = 1 }
		END { if (found) flush() }
	' "$1"
}

anchor() {
	printf '%s' "$1" | sed 's/^#* *//' | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9 _-]//g; s/ /-/g'
}

section() {
	# section FILE TITLE: emit one entry per H2 of FILE.
	f=$1
	title=$2
	echo
	echo "## $title"
	echo
	grep '^## ' "$f" | while IFS= read -r h; do
		name=$(printf '%s' "$h" | sed 's/^## //')
		line=$(first_para "$f" "$h")
		echo "- [$name]($BASE/$f#$(anchor "$h"))${line:+: $line}"
	done
}

{
	echo "# Remount"
	echo
	echo "> $(first_para README.md '# Remount' | sed 's/\*\*//g')"
	echo
	echo "Remount is an open protocol and a single static Go binary that gives an AI"
	echo "agent a workspace it can run on from anywhere: snapshotted, moved between"
	echo "machines, put to sleep, reattached mid-command, and never holding a"
	echo "credential. \`remount run RECIPE -- TASK\` launches a coding harness in one"
	echo "command. The normative wire protocol is [spec/PROTOCOL.md]($BASE/spec/PROTOCOL.md)."
	section README.md "README"
	section docs/tutorial.md "Tutorial"
	section docs/harness-integration.md "Harness integration"
	echo
	echo "## Optional"
	echo
	echo "- [design.md]($BASE/docs/design.md): why each piece is shaped the way it is, and the failure model."
	echo "- [operations.md]($BASE/docs/operations.md): tokens, TLS, backends, leases, backups."
	echo "- [ADRs]($BASE/docs/adr): one decision per file, never edited after the fact."
} > llms.txt

{
	echo "<!-- generated by scripts/gen-llms.sh from README.md, docs/tutorial.md, docs/harness-integration.md -->"
	for f in README.md docs/tutorial.md docs/harness-integration.md; do
		echo
		echo "<!-- $f -->"
		echo
		cat "$f"
	done
} > llms-full.txt

echo "wrote llms.txt ($(wc -l < llms.txt) lines) and llms-full.txt ($(wc -l < llms-full.txt) lines)"
