// Command security-profiles renders the backend capability matrix from the
// same Caps methods nodes advertise. Generation verifies its providers against
// cmd/remount/build_node.go's registry switch before emitting documentation.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"

	"remount.dev/remount/internal/profile"
	"remount.dev/remount/internal/proto"
	"remount.dev/remount/internal/workspace"
	"remount.dev/remount/internal/workspace/firecracker"
	"remount.dev/remount/internal/workspace/gvisor"
)

func main() {
	output := flag.String("output", "docs/security-profiles.md", "generated markdown path")
	check := flag.Bool("check", false, "fail when the generated file differs")
	flag.Parse()
	if flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "security-profiles: unexpected positional arguments")
		os.Exit(2)
	}
	body, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, "security-profiles:", err)
		os.Exit(1)
	}
	if *check {
		current, err := os.ReadFile(*output)
		if err != nil || !bytes.Equal(current, body) {
			fmt.Fprintln(os.Stderr, *output, "is stale; run go run ./scripts/security-profiles")
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*output, body, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "security-profiles:", err)
		os.Exit(1)
	}
}

func generate() ([]byte, error) {
	tmp, err := os.MkdirTemp("", "remount-security-profiles-")
	if err != nil {
		return nil, err
	}
	defer os.RemoveAll(tmp)
	process, err := workspace.NewProcess(filepath.Join(tmp, "process"))
	if err != nil {
		return nil, err
	}
	docker, err := workspace.NewDocker(filepath.Join(tmp, "docker"), "unused")
	if err != nil {
		return nil, err
	}
	// gVisor registration is gated by New's real runsc/netns probes. Caps is
	// deliberately static, so reading it cannot accidentally turn a failed
	// probe into an advertised backend.
	registry := workspace.NewRegistry(process, docker, &gvisor.Backend{}, &firecracker.Backend{})
	registered, err := registeredBackendNames()
	if err != nil {
		return nil, err
	}
	described := make(map[string]bool)
	for _, descriptor := range registry.Descriptors() {
		described[descriptor.Name] = true
	}
	for name := range registered {
		if !described[name] {
			return nil, fmt.Errorf("registered backend %q has no security-profile descriptor", name)
		}
	}
	for name := range described {
		if !registered[name] {
			return nil, fmt.Errorf("security-profile backend %q is not registered by buildNode", name)
		}
	}
	var out bytes.Buffer
	fmt.Fprint(&out, `# Security profiles

<!-- Code generated by go run ./scripts/security-profiles; DO NOT EDIT. -->

A profile is a placement contract. The control plane calls
`+"`proto.ValidateBackendSecurity`"+` against the capabilities a node actually
advertised; this table is explanatory and never grants authority. An unavailable
backend is absent, not healthy.

## Profile compatibility

The first three columns are the per-workspace placement contract of
`+"`proto.SecuritySpec.Profile`"+`. The last is the node-level runtime profile
of `+"`internal/profile`"+` (ADR 0089): the strongest `+"`--profile`"+` a node
registering only this backend could satisfy on its capabilities alone. They are
different contracts with similar names, and a backend can satisfy one and not
the other — gVisor satisfies the `+"`multi-tenant-isolated`"+` runtime profile
but not a workspace asking for `+"`multi_tenant`"+`, because that additionally
requires a microVM.

| Backend | local | isolated | multi_tenant | Runtime profiles satisfied |
|---|---:|---:|---:|---|
`)
	profiles := []string{proto.SecurityLocal, proto.SecurityIsolated, proto.SecurityMultiTenant}
	for _, descriptor := range registry.Descriptors() {
		fmt.Fprintf(&out, "| `%s`", descriptor.Name)
		for _, workspaceProfile := range profiles {
			mark := "yes"
			if err := proto.ValidateBackendSecurity(proto.SecuritySpec{Profile: workspaceProfile}, descriptor); err != nil {
				mark = "no"
			}
			fmt.Fprintf(&out, " | %s", mark)
		}
		fmt.Fprintf(&out, " | %s |\n", runtimeProfiles(descriptor))
	}
	fmt.Fprint(&out, `
A node registers more than one backend at a time, and every runtime-profile
predicate holds over *every* registered backend, so a fleet's real answer is
the weakest row it registers rather than the strongest. The column also assumes
no failing host check: `+"`profile.runtime.healthy`"+` folds what a live node's
`+"`Reprobe`"+` reports, and `+"`microvm`"+` additionally needs a live host
compatibility result, which a generated table cannot supply. Ask a running
deployment with `+"`remount doctor --profile`"+` or
`+"`remount conformance --profile`"+`.

`+"`local`"+` defaults to minimum isolation `+"`none`"+`. `+"`isolated`"+` requires
container isolation, a deny-default network, brokered secrets, required audit,
and an `+"`enforced_gateway`"+`. `+"`multi_tenant`"+` additionally requires a
microVM, sibling isolation, a network namespace, device isolation, and a backend
explicitly approved for multi-tenant placement.

## Advertised enforcement

| Backend | Isolation | Snapshot | Egress | Broker identity | Filesystem | Net namespace | Device isolation | Sibling isolation | Multi-tenant |
|---|---|---|---|---|---|---:|---:|---:|---:|
`)
	for _, descriptor := range registry.Descriptors() {
		s, r := descriptor.Security, descriptor.Runtime
		fmt.Fprintf(&out, "| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | %s | %s | %s | %s |\n",
			descriptor.Name, s.Isolation, r.Snapshots, s.EgressMode, s.BrokerIdentity, s.FilesystemBoundary,
			yesNo(s.NetworkNamespace), yesNo(s.DeviceIsolation), yesNo(s.SiblingIsolation), yesNo(s.MultiTenant))
	}
	fmt.Fprint(&out, `
## What the rows mean

- `+"`process`"+` is a filesystem jail and cooperative proxy. It is useful for
  local development. It is not an isolation or enforced-network boundary.
- `+"`docker`"+` provides a container, mount namespace and device filtering, but
  its broker proxy is cooperative. A process that ignores proxy variables can
  bypass it, so it cannot satisfy `+"`isolated`"+`.
- `+"`gvisor`"+` is registered only after `+"`runsc`"+`, rootfs and node-owned
  network probes pass. Its E4 integration lane must also be green for a release.
  It satisfies `+"`isolated`"+` but not the microVM requirement of
  `+"`multi_tenant`"+`.

The Firecracker descriptor shown here is the fail-closed, unverified zero
value. A live node advertises its microVM capabilities only after construction
probes its KVM, jailer, guest, volume and network adapters. Vendor provisioners
do not change these rows: caps come from the backend inside a machine, and
vendor pools remain one tenant per VM.

## Operational proof

Use `+"`remount nodes --json`"+` and `+"`remount doctor --deep --json`"+` to inspect
what a live node actually advertised and what it could verify. The release
claim for `+"`gvisor`"+` also requires the seven E4 denial checks in the isolation
workflow. Docker availability, KVM availability, or a skipped host check is not
a pass.
`)
	return out.Bytes(), nil
}

// registeredBackendNames reads the runtime registry's switch rather than
// maintaining a second unchecked list. A new backend therefore makes
// generation fail until this tool learns how to obtain its real Caps.
func registeredBackendNames() (map[string]bool, error) {
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		return nil, fmt.Errorf("locate generator source")
	}
	root := filepath.Clean(filepath.Join(filepath.Dir(source), "../.."))
	path := filepath.Join(root, "cmd/remount/build_node.go")
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, 0)
	if err != nil {
		return nil, fmt.Errorf("parse runtime backend registry: %w", err)
	}
	result := make(map[string]bool)
	for _, declaration := range file.Decls {
		function, ok := declaration.(*ast.FuncDecl)
		if !ok || function.Name.Name != "buildNode" {
			continue
		}
		ast.Inspect(function.Body, func(node ast.Node) bool {
			clause, ok := node.(*ast.CaseClause)
			if !ok {
				return true
			}
			for _, expression := range clause.List {
				literal, ok := expression.(*ast.BasicLit)
				if !ok || literal.Kind != token.STRING {
					continue
				}
				name, err := strconv.Unquote(literal.Value)
				if err == nil && name != "" {
					result[name] = true
				}
			}
			return true
		})
	}
	if len(result) == 0 {
		return nil, fmt.Errorf("runtime backend registry is empty")
	}
	return result, nil
}

// runtimeProfiles names every runtime profile (ADR 0089) one backend's own
// advertised capabilities satisfy, read from the same predicate the control
// plane schedules with rather than from a second hand-kept list. It is
// evaluated against a one-backend fleet with no host findings, which is the
// only thing a static document can honestly say: a real node's answer is a
// function of every backend it registered and of what its Reprobe reported a
// moment ago.
func runtimeProfiles(descriptor proto.BackendDescriptor) string {
	satisfied := profile.Satisfied([]proto.BackendDescriptor{descriptor}, nil)
	if len(satisfied) == 0 {
		return "none"
	}
	names := make([]string, 0, len(satisfied))
	for _, p := range satisfied {
		names = append(names, "`"+string(p)+"`")
	}
	return strings.Join(names, ", ")
}

func yesNo(value bool) string {
	if value {
		return "yes"
	}
	return "no"
}
